### ISSUE TITLE
find with string functions

### ISSUE THREAD

**Issue by andineck** [kofrasa/mingo#10]
I started using mingo. It's been really great so far.
What I am missing (or don't understand to do) is, finding documents with string functions like: `contains`, `startsWith`, `endsWith`.

How do I do this more elegant (contains):

```js
var result = Query.find(npm.rows, {$where: 'this.id.indexOf("express") !== -1'}).all();
// or
var result = Query.find(npm.rows, {id: /mocha/g}).all();
```

**Comment by kofrasa** [comment]
I believe the regular expression variant is clearer and more elegant.

**Comment by andineck** [comment]
is there also an elegant way without RegExp? 
I have to serialize the query object and reqular expressions are cumbersome for this use case.
Is there a way to `mixin` functions like: `contains`, `startsWith`, `endsWith`.

**Comment by kofrasa** [comment]
I decided to exclude special operators not found in the original MongoDB implementation. However, there is room for a feature that would allow registering custom operators. I did not think it would be necessary. With such a feature, that would mean loading up your custom operators into Mingo before running your serialized query.

**Comment by andineck** [comment]
makes sense, thx for the explanation.

**Comment by kofrasa** [comment]
Although this may long be overdue, I would like to say that [Custom Operators](https://github.com/kofrasa/mingo/wiki/Custom-Operators) are available now.
