### ISSUE TITLE
Query Against Non-Objects

### ISSUE THREAD

**Issue by JordanSinko** [kofrasa/mingo#103]
Hello - 

Hope I am in the right area. I am trying to use this awesome package but am getting a weird result using a query.

```
let query = new mingo.Query({
  scores: {
    $elemMatch: { $lt: 50 }
  }
});

// test if an object matches query
const result = query.test({ scores: [10, 50, 100] }); // expected true (10 < 50)
```

Does this not work with number types? If not, is there another way to query this out?

** Edit **
I was using this as an example https://docs.mongodb.com/manual/reference/operator/query/elemMatch/

**Comment by kofrasa** [comment]
Hi @JordanSinko, thanks for reporting this issue. 

There is a mistake in your translation of the example from `MongoDB` to `Mingo`. `$elemMatch` is a projection operator as noted on the documentation page which controls what should be returned from a complex valued field (i.e array or object) in a matched object. The correct signature is`mingo.Query(criteria, projection)`. See the correct us below.

```js
let query = new mingo.Query({}, {
  scores: {
    $elemMatch: { $lt: 50 }
  }
});

// test if an object matches query
const result = query.test({ scores: [10, 50, 100] }); // returns true
```

**Comment by kofrasa** [comment]
Looking at the docs from the link above `$elemMatch` is also a query operator but is not handled as such in `Mingo`. Your initial query is legitimate and should be properly handled. Currently, we treat criteria inputs that do not start with an operator as matching with `$eq`.

**Comment by JordanSinko** [comment]
Hi @kofrasa -

Thanks for looking into this. It appears to be applying $eq to simple types, so the `$lt` isnt being used. I have updated the example.

```
let query = new mingo.Query({
  scores: {
    $elemMatch: { $gt: 100 }
  }
});

// test if an object matches query
const result = query.test({ scores: [10, 50, 100] }); // returns true, should be false
```

It appears to be doing this:

```
let query = new mingo.Query({
  scores: {
    $elemMatch: { $eq: 100 }
  }
});
```

**Comment by kofrasa** [comment]
That is is
