### ISSUE TITLE
Problem with TypeScript definition

### ISSUE THREAD

**Issue by davidlav** [kofrasa/mingo#104]
Tried running this bare minimum code from the readme in TypeScript
```typescript
import mingo from 'mingo';

const query = new mingo.Query({
  type: "homework",
  score: { $gte: 50 }
});
```
and while it compiles without issue, I get this runtime error.
```
const query = new mingo.Query({
                        ^
TypeError: Cannot read property 'Query' of undefined
```

**Comment by kofrasa** [comment]
Hi @davidlav, thanks for reporting this.

The typescript above compiles down to;

```js
"use strict";
exports.__esModule = true;
var mingo_1 = require("./dist/mingo");
var query = new mingo_1["default"].Query({
    type: "homework",
    score: { $gte: 50 }
});
```

This is owing the the `import ... from` syntax which itself creates a new namespace for all members including a 'default' key when specific members are not specified.

To get around this change the import line to;

```js 
import * as mingo from './dist/mingo';
```

which generates the expected code
```js
"use strict";
exports.__esModule = true;
var mingo = require("./dist/mingo");
var query = new mingo.Query({
    type: "homework",
    score: { $gte: 50 }
});
```

I hope that helps.

**Comment by davidlav** [comment]
Gotcha, thanks!  Can I suggest adding that import line to the Usage section of the readme for other Typescript users?

**Comment by kofrasa** [comment]
will do. thanks
