### ISSUE TITLE
Use renovateapp to keep your dependencies up to date

### ISSUE THREAD

**Issue by stalniy** [kofrasa/mingo#107]
[Renovate bot](https://renovatebot.com/) is a really cool feature that allows to keep dependencies up to date. It automatically runs tests and if all good, updates automatically merges PR.

By the way, it's free and easy to install basic version. I use it for my project, you can check the config [here](https://github.com/stalniy/casl/blob/master/.renovaterc)

**Comment by kofrasa** [comment]
Thanks. Will take a look.

**Comment by kofrasa** [comment]
Added. Really nice tool indeed. Thanks again
