### ISSUE TITLE
sortBy(collection, fn, cmp) function crashes when collection key is "constructor"

### ISSUE THREAD

**Issue by belatrix-sgd** [kofrasa/mingo#109]
When sortingBy keys like "function", "constructor" a conditional hash[key] (line 534 - mingo.js) returns true even if the hash object does not contain an explicit "constructor" property.

This check should be done with Object​.get​OwnProperty​Names() to ensure the key is explicitly defined in that object.

**Comment by kofrasa** [comment]
Can you provide some more details such as the stack trace, query, and sample input?

**Comment by belatrix-sgd** [comment]
Hi FrancisThanks for answering so soon. I'll try to provide more details today but you can reproduce the error just trying to sort a list containing the string "constructor". I tried with last lib version. Sebastián On May 31, 2019 12:01 AM, Francis Asante <notifications@github.com> wrote:Can you provide some more details such as the stack trace, query, and sample input?
