### ISSUE TITLE
$slice works in a different way compared to mongodb

### ISSUE THREAD

**Issue by AntonSotirov** [kofrasa/mingo#11]
Expected: calling $slice with a single argument in **mongodb**, gets that many items from the array beginning from zero position.

Actual: Calling **mingo** with $slice and a single argument takes all items counting from that position in the array.

**Comment by AntonSotirov** [comment]
There is an issue with this implementation as well. It still doesn't behave as the original mongodb specification is.

For reference here are the tests for the $slice in [mongodb jstests code](https://github.com/mongodb/mongo/blob/7423c26ab95464a9b8f620ab4a11c297dc0621d5/jstests/core/slice1.js).

**Comment by kofrasa** [comment]
Yes. The reason for reopening the issue. Updating with a fix

**Comment by AntonSotirov** [comment]
There is one more issue with $slice. It currently excludes all other fields from the document. 
$slice should just affect the property that is being "sliced", and not interfere in any way with the exlusion or inclusion of other fields.

**Comment by kofrasa** [comment]
can you provide an example of this behaviour

**Comment by AntonSotirov** [comment]
Sure.

Example document:
{
  Text: "MyText",
  Array: [1,2,3] 
}

Fetching this document with a fields expression of:
{
  Array: { $slice: 1 }
}

should return 
{
  Text: "MyText",
  Array: [1],
  _id: <....>
}

Notice that the Text and _id field will be included.
Furthermore, you can mix $slice with field exclusion and inclusion without affecting them:

Ex.
{
  Array: { $slice: 1 },
  Text: 0
}

{
  Array: { $slice: 1 }
  Text: 1,
  _id: 0
}

etc.

Current implementation of mingo returns only the Array field when $slice is used.

**Comment by kofrasa** [comment]
Thanks. I am a bit surprised. This looks like a special case in MongoDB. The other projection operator $elemMatch does not behave the same way.

**Comment by AntonSotirov** [comment]
That IS surprising. Didn't know about $elemMatch. I would have expected that it works the same as $slice.

**Comment by kofrasa** [comment]
anyway. I have a fix coming up.

**Comment by kofrasa** [comment]
issue resolve in release 0.3.3
