### ISSUE TITLE
$facet in aggregation pipeline (bug)

### ISSUE THREAD

**Issue by lionben89** [kofrasa/mingo#110]
Hi,
When I tried to do $facet as the 3 operator in a aggregate operators array, i go thrown an error, because
the facet operator code is :
export function $facet (collection, expr, opt) {
  return collection.transform(array => {
    return [ objectMap(expr, pipeline => aggregate(array, pipeline)) ]
  }).first()
}

which enable the this.__first flag

and cause

_validate () {
    if (this.__first) throw new Error("Cannot add iteratee/transform after `first()`")
}

to throw an error.

when i comment the throw error line, the code works fine.

**Comment by kofrasa** [comment]
Thanks for reporting this @lionben89. I will make some time to look at this issue but I also welcome pull requests.

Please provide sample input data and query that produces this issue?
