### ISSUE TITLE
$project not projecting new array fields

### ISSUE THREAD

**Issue by JordanSinko** [kofrasa/mingo#119]
I'm not sure how Mingo compares to the current implementation of Mongo syntax, but I am not able to project an array with sub expressions.

```javascript
const { aggregate } = require("mingo");

const event = { x: "hi" };

const result = aggregate(
  [{ event }],
  [
    {
      $project: {
        myArray: ["$event.x"]
      }
    }
  ]
);

console.log(result); // actual:[{}], expected:[{myArray: ['hi']}]

```

Notes: https://docs.mongodb.com/manual/reference/operator/aggregation/project/#new-array-fields

**Comment by kofrasa** [comment]
Hey @JordanSinko, thanks for reporting this. 

This is looks like a bug unless the behaviour of MongoDB aggregation changed in new versions. I will make some time to research it but if you have already tracked it down, I am happy to accept a PR.
