### ISSUE TITLE
proposed $toDecimal and other conversion functions found in 4.x

### ISSUE THREAD

**Issue by billreynolds007** [kofrasa/mingo#120]
I came upon an example MongoDB query which used $toDecimal and tried it with Mingo. Mingo was not aware of this function. Attached are proposed functions for $toBool, $toDate, $toDecimal, $toDouble, $toInt, $toLong, and $toString. I was not sure what to do with $toObjectId.
I appreciate the updates and the incorporation of the locale sorting feature.
[mingoProposedConversionFunctions.txt](https://github.com/kofrasa/mingo/files/4135066/mingoProposedConversionFunctions.txt)

**Comment by kofrasa** [comment]
This library is a bit out of date at the moment. My reasoning has been to keep it lean and take contributions as people use new operators not yet supported. There were a flood of new operators from MongoDB version 4.0 that I haven't gotten around to implementing yet.

I am happy to accept a PR for any of them you are using currently and have implemented.

Thanks.
