### ISSUE TITLE
proposed update to $trunc to spport optional 'place' argument

### ISSUE THREAD

**Issue by billreynolds007** [kofrasa/mingo#121]
Mingo is not aware of the optional 'place' argument in $trunc. Here is the proposed code to be aware of that optional argument. The function call template is { $trunc : [ &lt;number&gt;, &lt;place&gt; ] }.
For reference see https://docs.mongodb.com/manual/reference/operator/aggregation/trunc/.

[mingoProposedTruncateUpdate.txt](https://github.com/kofrasa/mingo/files/4135075/mingoProposedTruncateUpdate.txt)

**Comment by kofrasa** [comment]
Thanks for the contribution @billreynolds007. This looks like it was added later. 

I will appreciate send a PR with the new improvements. Thanks again.
