### ISSUE TITLE
Library does not work on IE11 because of Symbol being undefined

### ISSUE THREAD

**Issue by squallstar** [kofrasa/mingo#124]
Hello, is there any chance we can get a version of the dist js which works on IE11?

It currently doesn't work because `Symbol is undefined` so a polyfill will be necessary during the transpiling.

I have tested the latest JS files in the dist folder against IE11.

Many thanks.

**Comment by kofrasa** [comment]
Hi @squallstar, thanks for opening this issue. 

I am not sure adding a polyfill is the right thing to do here. The [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) object is not required to run `Mingo` and is only added as a convenience to enable [for..of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) style iteration.

Perhaps the correct thing to add a guard to test for the `Symbol` support and only add the iterator if it is available in the environment. This frees up users to bring their own polyfill if they want to use the `for..of` style syntax.

**Comment by squallstar** [comment]
@kofrasa thanks! Really appreciate the patch you made. Are all `dist` files up to date so that I can make use of your patch?

**Comment by kofrasa** [comment]
Yes, the changes are available in `dist` for release `2.5.0`. All files are up to date and should run fine even in environments without `Symbol` support.

Happy Coding.

**Comment by squallstar** [comment]
@kofrasa unfortunately this is still an issue on IE11 because "Object.assign" is not supported (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).

**Comment by kofrasa** [comment]
I will make the fix as part of `3.0.0` which attempts to baseline IE support to version 9.

**Comment by squallstar** [comment]
@kofrasa thanks, meanwhile I have added the above polyfill to make it work.
