### ISSUE TITLE
New date operators and timezone support on mainstream?

### ISSUE THREAD

**Issue by par6n** [kofrasa/mingo#135]
First of all, on behalf of my team, I want to thank you and all of the contributors for maintaining this great project. It really makes life easier for us!

We're interested in your recent commit (84575ce65e539c77daa38ffbcf50afee612aa8a7) since it creates new opportunities for us to release more features. But as I've understood, these new operators and timezone support are currently on development branch.

Is there any release plan or estimation regarding when it'd reach the mainstream? I, personally, am interested to contribute to these features to get it to mainstream sooner.

**Comment by kofrasa** [comment]
Hi @par6n, so I have been busy with a major `3.0.0` release which converts the project to typescript and addresses most all of the outstanding issues including timezone support for dates.

Although I cannot promise a hard timeline or release, early next week or earlier seems very likely. The development branch is almost ready to merge barring fixing #97 and adding some needed documentation to the readme to highlight breaking changes introduced.

There are still some operators not implemented and I do welcome PRs. For now though it might be best to publish `3.0.0` first before accepting further work. If you are keen to test out the development version please go ahead. Will appreciate some feedback in how it fits into your use case. One of the new features I am excited about is that this version supports tree-shaking unused operators not explicitly registered if bundle size is a concern for use in client environments.

Thanks for finding this library useful and do look forward to the latest version.

**Comment by kofrasa** [comment]
Release `3.0.0` published
