### ISSUE TITLE
Using $hour in query via $expr?

### ISSUE THREAD

**Issue by par6n** [kofrasa/mingo#137]
I'm trying to test an object against the query I wrote which goes as following:
```js
{
  $expr: {
    $gte: [
      {
        $hour: {
          date: { $toDate: '$dateField' },
          timezone: 'Asia/Tehran',
        }
      },
      0
    ]
  }
}
```

It works with MongoDB itself (tested against v4.2), but the same query doesn't work when it's converted to Mingo.

```js
const query = {
  $expr: {
    $gte: [
      {
        $hour: {
          date: { $toDate: '$dateField' },
          timezone: 'Asia/Tehran',
        }
      },
      0 // I've set it to zero deliberately
    ]
  }
}

const mingoQuery = new mingo.Query(query)

mingoQuery.test({ dateField: new Date().getTime() }) // false
```

It also doesn't work by removing `$toDate` and `getTime()` from code.

**Update**: I dug a little deeper and by putting tracers around the code, I understood that `$hour` handle isn't being called. I found out that the pipeline won't go deeper than `$gte` operator handler, because it just compares `{ $hour: ... }` and `0` and they can't be compared, naturally.
I have a feeling that maybe I'm writing the query the wrong way and there's a better (and working) approach to this.

**Comment by kofrasa** [comment]
Starting in `3.0.0` the expression operators must be loaded explicitly. This enables tree-shaking so that any unused operators is not bundled. You can use one of the two methods below.

### 1. Import all operators
Simpler but will add the entire library to bundle.

```js
import 'mingo/init/system'
```

### 2. Import the required operators explicitly 

```js
import { useOperators, OperatorType } from 'mingo/core'
import { $hour } from 'mingo/operators/expression/date'
import { $toDate } from 'mingo/operators/expression/type'

useOperators(OperatorType.EXPRESSION, { $hour, $toDate })
```

**Comment by kofrasa** [comment]
You can see the full documentation here. http://kofrasa.net/mingo/index.html
