### ISSUE TITLE
$elemMatch fails on undefined array

### ISSUE THREAD

**Issue by edqd** [kofrasa/mingo#139]
Hello,
first of all, thanks for this great lib :)
since version 3.0.0, we are seeing an error being thrown on processing of $elemMatch when there is not array present, is this intended behavior? I didn't find anything on this in the release docs or any other issue on this subject hence I'm creating this one.
A simple example to demo the error: https://runkit.com/embed/xypukhcz8gg2

**Comment by kofrasa** [comment]
Hi @edqd,  thanks for reposting the issue. This is a regression and will be fix in a minor release
