### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by carsonfarmer** [kofrasa/mingo#140]
With update to 3.0.1, I'm now getting the following error in a Typescript project. If I run this with (say) mocha and the `--require esm` flag, it compiles fine.

```
/Users/.../node_modules/mingo/query.js:1
import { assert, each, inArray, isObject, isOperator, normalize } from './util';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/.../node_modules/....js:23:17)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```

This is for a library meant to be consumed by others, any idea how to handle this properly so they don't have to?

**Comment by carsonfarmer** [comment]
For context, I'm import like this:

```
import { Query } from 'mingo/query'
import { resolve } from 'mingo/util'
```

Which might be part of the problem?

**Comment by carsonfarmer** [comment]
Yes, this appears to be the issue. By importing the sub-modules directly like this, they aren't wrapped in `esm`, hence the error. Closing this as I suspect this is entirely pilot error and functioning as expected. Though perhaps the docs could reflect this requirement?

**Comment by kofrasa** [comment]
Hi @carsonfarmer, thanks for reporting this issue. The esm loader should work for sub-modulesa s well.

An example from the shell.

```js
➜  ~ node -r esm
Welcome to Node.js v13.11.0.
Type ".help" for more information.
> import { resolve } from 'mingo/util'
undefined
> resolve
[Function: resolve]
> import json from 'mingo/package.json'
undefined
> json.version
'3.0.1'
>
```

Do you mind to elaborate on how you are consuming the library?

**Comment by carsonfarmer** [comment]
Right, with the esm module required, all works nicely. I'm in a remote node environment where I don't have access to how node is started, so I can't use cli flags to include the esm module. This is why the 'main' module being wrapped in esm is helpful. For additional context, the remote code is actually being dynamically compiled from typescript and run on the remote node, within a [tslab notebook](https://github.com/yunabe/tslab).
