### ISSUE TITLE
mingo + ts-jest creates memory leak to crash

### ISSUE THREAD

**Issue by j** [kofrasa/mingo#145]
Latest mingo with ts-jest creates memory leak / heap limit error.

Here's a simple repro: https://github.com/j/mingo-error

**Comment by kofrasa** [comment]
Thanks a lot for the repro project. This is quite a weird issue to debug.  

I haven't delved deeper into the node memory management to fully understand what could be happening as I suspect it would be an unnecessary rabbit hole.

Nonetheless I found these possibly related issues searching the `jest` project .

- https://github.com/facebook/jest/issues/9959
- https://github.com/facebook/jest/issues/9980
- https://github.com/facebook/jest/issues/9346

It is rather unlikely that querying a single object should cause GC issues. Over 500 unit tests run for `mingo` without any memory problems. The culprits if any would be the `esm` module introduce in `3.0.0` or `jest` itself. The shear number of memory leak issues open with the `jest` project leads me to believe it is responsible.

Are you using the same version of `jest` without error against older versions of `mingo` (e.g `2.x.x` without ESM support)?

**Comment by kofrasa** [comment]
See comment https://github.com/facebook/jest/issues/7874#issuecomment-477316116 which suggests the same type of problem described in this issue.

Please open an issue or add your vote to a relevant one in the `jest` project.

**Comment by j** [comment]
@kofrasa 

Yes, I have dozens of dependencies and a huge mono-repo under one jest test suite, and it was just the `mingo` v3 version that caused the crash.  The error mentioned `esm` from what I remember.  Reverting back to `2.x.x` fixed the issue, so I'm running the old version of `mingo` ATM.  I used the same versions of everything else and tracked it down to `mingo`.

**Comment by j** [comment]
You can clone my repository, set `mingo` to `2.x` and tests will pass.

**Comment by kofrasa** [comment]
The fingers point to the dependency on [esm](https://www.npmjs.com/package/esm). Something is amiss in how it interacts with [jest](http://npmjs.com/package/jest).

In any case, that does not have to be a hard dependency. Users are free to pick their preferred bundling solution so the right thing to do here is remove it.

**Comment by kofrasa** [comment]
Fix in latest version. `esm` module removed.

```
➜  mingo-error git:(master) ✗ node_modules/jest/bin/jest.js
 PASS  src/query.test.ts
  ✓ works (3 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.831 s, estimated 3 s
Ran all test suites.
➜  mingo-error git:(master) ✗
```
