### ISSUE TITLE
$not operator does not handle non-array values correctly.

### ISSUE THREAD

**Issue by redgeoff** [kofrasa/mingo#146]
I'd like to start by saying that your library looks awesome!

I'm considering making mingo the MongoDB query engine for [MSON](https://github.com/redgeoff/mson) as it implements aggregation, a very needed concept that is currently missing.

My hold up is that in my quick tests, it looks like there may be a problem with basic operators like `$not`. For example, take a look at [this codsandbox](https://codesandbox.io/s/mingo-aggregation-w78ck?file=/src/index.js) and you'll see that the  output of `bar` is `true` and **not** the negation of `foo`. In other words, shouldn't `bar`=`false`?

For convenience, here is the code:
```js
import { Aggregator } from "mingo/aggregator";
import "mingo/init/system";

const collection = [
  {
    foo: true
  }
];

let agg = new Aggregator([
  {
    $project: {
      bar: {
        $not: "$foo"
      }
    }
  }
]);

let result = agg.run(collection);
console.log(result);
```

By comparison, this is how [MongoDB handles this same aggregation](https://mongoplayground.net/p/8gWAbrM9lJc). Please note that the Result has `bar`=`false`

Configuration:
```js
[
  {
    foo: true
  }
]
```

Query:
```js
db.collection.aggregate([
  {
    $project: {
      bar: {
        $not: "$foo"
      }
    }
  }
])
```

Result:
```js
[
  {
    "_id": ObjectId("5a934e000102030405000000"),
    "bar": false
  }
]
```

**Comment by kofrasa** [comment]
Thanks and I appreciate you considering this library.

On the issue itself, the `$not` operator is actually implemented although it seems there is an inconsistency with `MongoDB`.

The [documentation](https://docs.mongodb.com/manual/reference/operator/aggregation/not/#exp._S_not) does say the value for the expression when used in an aggregation context must be `[ <expression> ]`, that is, it must be wrapped in an array. If you changed your example query to `bar: { $not: [ "$foo" ] }`, you will get the expected result. See [example](https://runkit.com/embed/q0piw2qtg5pf)

Nonetheless given the inconsistency it is fair to treat this a bug. The documentation alone does not constitute a spec of any kind.

**Comment by redgeoff** [comment]
Awesome, thanks for the clarification! I'll leave this issue open to leave a record of the bug.
