### ISSUE TITLE
"query criteria must be an object" is thrown for object literals in nuxt.js environments

### ISSUE THREAD

**Issue by TimoStolz** [kofrasa/mingo#149]
When I use mingo in a nuxt.js project, the snippet `new Query({ something: { $eq: 'awesome' } })` leads to an error complaining "query criteria must be an object". However in this snippet, there is an Object literal. While debugging the application I noticed that nuxt.js and mingo were using different Object-constructors—possibly due to polyfilling, but I don't know exactly. They looked pretty equal, but had different identities. That's why isObject(v) returned false.

I could work around the issue by patching mingo to use lodash's [code of _.isPlainObject()](https://github.com/lodash/lodash/blob/aa1d7d870d9cf84842ee23ff485fd24abf0ed3d1/isPlainObject.js). Then the above snippet was working in nuxt.js, too.

(When setting up a project with Vue CLI, the error was not occurring. Possibly, it is sensitive to some JS environments / bundlers / ….)

Something similar has already been reported in issue #141, _Originally posted by @carsonfarmer in https://github.com/kofrasa/mingo/issues/141#issuecomment-639662570_

> I fact, I am dealing with object literals... but they are being run through a compiler (bundler) which is 'converting' them to something that doesn't satisfy the constraints in isObject, hence the issue. For the time being, I am also actually taking advantage of the unsafe behavior of isObject to trick it into thinking my objects _are_ indeed object literals... this should work for now 🤷.

**Comment by kofrasa** [comment]
Hi @TimoStolz, thanks for reporting this.

So i explained in https://github.com/kofrasa/mingo/issues/141, validating literal objects early helps avoid surprises down the line for users who have custom constructors on objects and expect them to be preserved. Using literals like in your example should fail. See [example](https://runkit.com/embed/tj3hlla0cxbv)

If you are getting an error something be very off in your environment. The plain object implementation from lodash will not provide the guarantee also because it relies on `Object.getPrototypeOf` which also can be overridden, although it is a better alternative.

There aren't many good solutions here because we are working in a dynamic environment but I think the right thing to do is remove the validation entirely.

**Comment by TimoStolz** [comment]
At the moment, I'm basically patching the library using [patch-packge](https://www.npmjs.com/package/patch-package) and the attached patch file. Take care: this introduces lodash as a dependency! However, as lodash already is a dependency of my project, for me, this is fine.

```diff
diff --git a/node_modules/mingo/core.js b/node_modules/mingo/core.js
index 3fb76c2..520e04f 100644
--- a/node_modules/mingo/core.js
+++ b/node_modules/mingo/core.js
@@ -30,7 +30,7 @@ util_1.each(OperatorType, function (cls) {
  */
 function validateOperators(operators) {
     util_1.each(operators, function (v, k) {
-        util_1.assert(v instanceof Function && util_1.isOperator(k), "invalid operator specified");
+        util_1.assert(typeof v === 'function' && util_1.isOperator(k), "invalid operator specified");
     });
 }
 /**
diff --git a/node_modules/mingo/util.js b/node_modules/mingo/util.js
index 044c220..1dd32d5 100644
--- a/node_modules/mingo/util.js
+++ b/node_modules/mingo/util.js
@@ -74,9 +74,11 @@ exports.isString = isString;
 function isNumber(v) { return !isNaN(v) && typeof v === JsType.NUMBER; }
 exports.isNumber = isNumber;
 exports.isArray = Array.isArray || (function (v) { return v instanceof Array; });
-function isObject(v) { return !!v && v.constructor === Object; }
+const _isPlainObject = require('lodash/isPlainObject')
+const _isObjectLike = require('lodash/isObjectLike')
+function isObject(v) { return _isPlainObject(v) }
 exports.isObject = isObject;
-function isObjectLike(v) { return v === Object(v); } // objects, arrays, functions, date, custom object
+function isObjectLike(v) { return _isObjectLike(v) } // objects, arrays, functions, date, custom object
 exports.isObjectLike = isObjectLike;
 function isDate(v) { return v instanceof Date; }
 exports.isDate = isDate;
```

**Comment by kofrasa** [comment]
After a bit of investigation and new findings, I have settled on the `lodash` approach. Between an object's constructor and prototype, the former is more likely to be modified. Validating against the prototype restricts the definition of a plain object which I think is better for most cases.

Basically, a plain object becomes either; an object literal, or any object with a null prototype. This is sufficient given that overriding an object's prototype correctly modifies the constructor but not vice versa. The following code implements the predicate.

```js
const OBJECT_PROTOTYPE = Object.getPrototypeOf({})
const OBJECT_TO_STRING = Object.prototype.toString
const OBJECT_TAG = '[object Object]'
function isObject(v) {
  if (!v) return false
  let proto = Object.getPrototypeOf(v)
  return (proto === OBJECT_PROTOTYPE || proto === null) && OBJECT_TAG === OBJECT_TO_STRING.call(v)
}
```
