### ISSUE TITLE
Exclusive select projections seem to be broken

### ISSUE THREAD

**Issue by vdininski** [kofrasa/mingo#15]
Example data model:

```javascript
var user = {
  Name: "Mingo",
  Age: 20,
  _id: 1
}
```

Using something along the line of `var query = new Mingo.Cursor(collection, {}, {Name: 0})` I expect the result to be:

```javascript
{
  Age: 20,
  _id: 1
}
```

instead it is:

```javascript
{
  _id: 1
}
```

**Comment by kofrasa** [comment]
@AntonSotirov fixed this issue. Will be resolved in the next release :)
