### ISSUE TITLE
.sort() does nothing in 2.2.4

### ISSUE THREAD

**Issue by Nashorn** [kofrasa/mingo#153]
Running 2.2.4 still because I cannot find a single .js distributable of latest 3.x.
.sort() does not work on the cursor, it returns [] unsorted. I looked at the src
and sort() does not do much.

Any suggestions?
```
/**
   * Returns results ordered according to a sort specification.
   * @param {Object} modifier an object of key and values specifying the sort order. 1 for ascending and -1 for descending
   * @return {Cursor} Returns the cursor, so you can chain this call.
   */
  sort (modifier) {
    this.__operators.push({ '$sort': modifier });
    return this
  }
```

**Comment by kofrasa** [comment]
You need to call `all()` on the cursor to realize the output. The methods only update the `Cursors` internal state and do not take immediate effect.
