### ISSUE TITLE
add option to disable $where clause

### ISSUE THREAD

**Issue by shanejonas** [kofrasa/mingo#155]
**Is your feature request related to a problem? Please describe.**
I'm trying to use mingo to allow querying a just subset of data via an API, but i'd like to not allow `$where` or any eval clauses.

**Describe the solution you'd like**
As a user of `mingo`, for security purposes, I'd like to not allow any evals in queries such as `$where: "this.foo && this.bar"`, is theres a way to disable it?

**Additional context**
Heres the reference on how to disable this in the mongodb documentation:

![image](https://user-images.githubusercontent.com/364566/93795825-cab6fe80-fbee-11ea-9d38-4990e292548b.png)

> source: https://docs.mongodb.com/manual/reference/operator/query/where/#javascript-enablement

**Comment by kofrasa** [comment]
This seems reasonable. I will see if I can add it to the next release

**Comment by kofrasa** [comment]
In the next release `$where` will not be registered by default and must be included explicitly by users.

**Comment by kofrasa** [comment]
Fixed in [4.0.0](https://github.com/kofrasa/mingo/releases/tag/4.0.0)
