### ISSUE TITLE
Updated lookup example

### ISSUE THREAD

**Issue by billreynolds007** [kofrasa/mingo#162]
Hi Kofrasa, Many thanks for incorporating the $lookup extension concept I outlined last year.
I was trying to put together an example withthe 4.0.0 release.
I have reviewed the references guide at
http://kofrasa.net/mingo/modules/_operators_pipeline_lookup_.html#_lookup

I am unable to get the callback option to be called. Here is what I have

    const mingo = require('mingo')
    var { Aggregator } = require('mingo/aggregator')
    var { useOperators, OperatorType } = require('mingo/core')
    var { $match, $lookup } = require('mingo/operators/pipeline')
    useOperators(OperatorType.PIPELINE, { $match, $lookup })
    var doc = { who: 'johnny', score: 75, type: 'homework' };
    var docs = [doc];
    var students = [ {nickName: 'johnny', first: 'John', last: 'Doe'} ];
    var collectionResolver = function(collectionName)
         {
         return students; // Demo purposes
         };
    let agg = new Aggregator([
      {'$match': { "type": "homework"}},
      {'$lookup': { 
            from: 'students', // The STRING!
            localField: "who",
            foreignField: "nickName",
            as: "profile"
 	    }
        }
    ])
    let result = agg.run(docs)
    console.log( JSON.stringify(result, null, 2) );

I added the second line below to ..\node_modules\mingo\operators\pipeline\lookup.js

    function $lookup(collection, expr, options) {
    console.log(arguments);

Running this shows the following in the console.

    node testMingoLookup.js
    [Arguments] {
      '0': Iterator {
        __iteratees: [ [Object] ],
        __first: false,
        __done: false,
        __buf: [],
        __next: [Function]
      },
      '1': {
        from: 'students',
        localField: 'who',
        foreignField: 'nickName',
        as: 'profile'
      },
      '2': { idKey: '_id' }
    }
    
.\node_modules\mingo\operators\pipeline\lookup.js:17
            ? options === null || options === void 0 ? void 0 : options.collectionResolver(expr.from) : expr.from;
                                                                             ^
    TypeError: options.collectionResolver is not a function
        at $lookup (C:\mongonode\node_modules\←[4mmingo←[24m\operators\pipeline\lookup.js:17:69)
        at Aggregator.stream (C:\mongonode\node_modules\←[4mmingo←[24m\aggregator.js:36:28)
        at Aggregator.run (C:\mongonode\node_modules\←[4mmingo←[24m\aggregator.js:48:21)
        at Object.<anonymous> (C:\mongonode\testMingoLookup.js:28:18)
    ←[90m    at Module._compile (internal/modules/cjs/loader.js:955:30)←[39m
    ←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)←[39m
    ←[90m    at Module.load (internal/modules/cjs/loader.js:811:32)←[39m
    ←[90m    at Function.Module._load (internal/modules/cjs/loader.js:723:14)←[39m
    ←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)←[39m
    ←[90m    at internal/main/run_main_module.js:17:11←[39m

Thanks again for the Mingo work.
 Bill

**Comment by kofrasa** [comment]
You have to pass the resolver as part of the options.

```javascript

let opts = {
  collectionResolver: function(){...}
}

let agg = new Aggregator([
  {'$match': { "type": "homework"}},
  {'$lookup': { 
        from: 'students', // The STRING!
        localField: "who",
        foreignField: "nickName",
        as: "profile"
    }
    },
    opts
])
```
