### ISSUE TITLE
{ $type: [BsonType, BsonType, ...] } not working

### ISSUE THREAD

**Issue by shota-f** [kofrasa/mingo#167]
Thanks for the awesome library @kofrasa 

Version: 4.1.2

As explained in https://docs.mongodb.com/manual/reference/operator/query/type/
The $type expression can also accept an array of BSON types in mongodb.

But in mingo, the following code returns unexpected result.

```
const query = new mingo.Query({
  val: { $type: ["string", "bool"] },
});

const collection = [{ val: "hoge" }, { val: true }, { val: 777 }];

// expect [ { val: "hoge" }, { val: true } ]
// but [ ]
console.log(query.find(collection).all());
```

**Comment by kofrasa** [comment]
Hi @shota-f, thanks for spotting this. 

You are correct that an array of types is not currently supported. I accept PRs if you want to take a stab at the implementation, you can find the code here [$type](https://github.com/kofrasa/mingo/blob/master/src/operators/_predicates.ts#L292).

```js
export function $type(
  a: AnyVal,
  b: number | string,
  options?: Options
): boolean 
```

The signature should change to something like;

```js
type BSONType = number | string | Array<number> | Array<string>

export function $type(
  a: AnyVal,
  b: BSONType
  options?: Options
): boolean 
```

And then the array handled appropriately for the conjunction check.

**Comment by shota-f** [comment]
Thanks for the clear explanation.
I've sent a pull request. #167
