### ISSUE TITLE
Group by multiple fields not supported?

### ISSUE THREAD

**Issue by RobertBaron** [kofrasa/mingo#17]
Hi, 

I am playing with your framework, so far I love the way it works.. Anyway I want to "report" the following issue.

On the mongo shell I execute the following query:
db.XXX.aggregate([{"$match":{}},{"$group":{"_id":{"hour":"$date_buckets.hour","keyword":"$Keyword"},"total":{"$sum":1}}},{"$sort":{"total":-1}},{"$limit":5},{"$project":{"_id":0,"hour":"$_id.hour","keyword":"$_id.keyword","total":1}}])

* Notice the multiple field grouping.
And this is the result:
{ "total" : 2, "keyword" : "Bathroom Cleaning Tips" }
{ "total" : 1, "keyword" : "best way to clean a bathroom" }
{ "total" : 1, "keyword" : "Cleaning Bathroom Tips" }
{ "total" : 1, "keyword" : "unclog bathtub drain" }
{ "total" : 1, "keyword" : "Drain Clogs" }

Same query applied using mingo
 var agg = new Mingo.Aggregator(
            [{
                $match: {}
            },{
                $group: {
                    _id: {
                        hour: "$date_buckets.hour"
                        , keyword: "$Keyword"
                    },
                    total: {
                        $sum: 1
                    }
                }
            },{
                $sort: {
                    total: -1
                }
            },{
                $limit: 5
            },{
                $project: {
                    _id:0
                    , hour: "$_id.hour"
                    , keyword: "$_id.keyword"
                    , total:1
                }
            }]
        );

And this is the result:

  { "total" : 6, "keyword" : "Bathroom Cleaning Tips" }
  { "total" : 6, "keyword" : "best way to clean a bathroom" }
  { "total" : 6, "keyword" : "Cleaning Bathroom Tips" }
  { "total" : 6, "keyword" : "unclog bathtub drain" }
  { "total" : 6, "keyword" : "Drain Clogs" }

This is the data I am using it contains 6 rows:
[{"date_buckets":{"date":"2015-04-29T00:17:03.107Z","day":28,"hour":18,"minute":17,"sec":3,"hour_minute":"18:17"},"Keyword ID":"sr3_4VzRD3sp","Creative ID":"5184986203","Keyword":"Bathroom Cleaning Tips","Match Type":"be","Device":"m","Conversions":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],"Revenues":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],"account_id":"baron"},{"date_buckets":{"date":"2015-04-29T00:17:03.107Z","day":28,"hour":18,"minute":17,"sec":3,"hour_minute":"18:17"},"Keyword ID":"sr3_K1iQOeXy","Creative ID":"5184986241","Keyword":"Cleaning Bathroom Tips","Match Type":"bb","Device":"c","Conversions":[5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0],"Revenues":[5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0],"account_id":"baron"},{"date_buckets":{"date":"2015-04-29T00:17:03.108Z","day":28,"hour":18,"minute":17,"sec":3,"hour_minute":"18:17"},"Keyword ID":"sr3_sl0C3VAYk","Creative ID":"44210589597","Keyword":"best way to clean a bathroom","Match Type":"b","Device":"c","Conversions":[4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0],"Revenues":[4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0],"account_id":"baron"},{"date_buckets":{"date":"2015-04-29T00:17:03.108Z","day":28,"hour":18,"minute":17,"sec":3,"hour_minute":"18:17"},"Keyword ID":"sr3_4VzRD3sp","Creative ID":"5184986204","Keyword":"Bathroom Cleaning Tips","Match Type":"be","Device":"c","Conversions":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],"Revenues":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],"account_id":"baron"},{"date_buckets":{"date":"2015-04-29T00:17:03.107Z","day":28,"hour":18,"minute":17,"sec":3,"hour_minute":"18:17"},"Keyword ID":"sr3_HZAarvKy","Creative ID":"6074827333","Keyword":"Drain Clogs","Match Type":"bp","Device":"c","Conversions":[1,0,0,1,0,0,0,0,0],"Revenues":[5,0,0,5,0,0,0,0,0],"account_id":"baron"},{"date_buckets":{"date":"2015-04-29T00:17:03.107Z","day":28,"hour":18,"minute":17,"sec":3,"hour_minute":"18:17"},"Keyword ID":"sr3_irU8fFk0","Creative ID":"6074827289","Keyword":"unclog bathtub drain","Match Type":"bp","Device":"c","Conversions":[1,0,0,1,0,0,0,0,0],"Revenues":[5,0,0,5,0,0,0,0,0],"account_id":"baron"}]

I will try to figure it out whats going on, but probably you are fastest than me.
Thanks, Robert Baron.

**Comment by kofrasa** [comment]
Thank you Robert. We will look into that soon.

**Comment by kofrasa** [comment]
fix included. next release coming soon.

**Comment by RobertBaron** [comment]
I just test this in the new release and data it is not matching with the comparing against mongo db :(
Thanks
--
Robert Baron.

**Comment by kofrasa** [comment]
Hello Robert,
Your test case was included as a unit test for this fix.
See [test here](https://github.com/kofrasa/mingo/blob/master/test/aggregation.js#L151)
The test excludes the *_id* field explicitly, which would be added automatically otherwise.
If there are still issues, can you provide more details of the query you are currently running.

**Comment by RobertBaron** [comment]
Hi Kofrasa,

I think I understand the "issue" ( I don't think is a bug or something similar ) anyway I want to explain why I has confused, I create a repo on: https://github.com/RobertBaron/Mingo_tmp_test_case with some test files ( for demo: code may not be the best ;) 
npm install
and then 

$ node test1.js 
Mongo result!******
[ { total: 2, hour: 18, keyword: 'Bathroom Cleaning Tips' },
  { total: 1, hour: 18, keyword: 'Drain Clogs' },
  { total: 1, hour: 18, keyword: 'Cleaning Bathroom Tips' },
  { total: 1, hour: 18, keyword: 'unclog bathtub drain' },
  { total: 1, hour: 18, keyword: 'best way to clean a bathroom' } ]
Mingo result!$$$$$
[ { hour: 18, keyword: 'Bathroom Cleaning Tips', total: 2 },
  { hour: 18, keyword: 'Cleaning Bathroom Tips', total: 1 },
  { hour: 18, keyword: 'best way to clean a bathroom', total: 1 },
  { hour: 18, keyword: 'Drain Clogs', total: 1 },
  { hour: 18, keyword: 'unclog bathtub drain', total: 1 } ]

In both cases data is the same but what happen if I use different hours for the rows?

$ node test2.js 
Mongo result!******
[ { total: 3, hour: 5, keyword: 'autocad' },
  { total: 2, hour: 12, keyword: 'autocad' },
  { total: 1, hour: 14, keyword: 'autocad' },
  { total: 1, hour: 0, keyword: 'autocad light' },
  { total: 1, hour: 1, keyword: 'autocad lt 2015' } ]
Mingo result!$$$$$
[ { hour: 5, keyword: 'autocad', total: 3 },
  { hour: 12, keyword: 'autocad', total: 2 },
  { hour: 10, keyword: 'autocad', total: 1 },
  { hour: 11, keyword: 'autocad', total: 1 },
  { hour: 12, keyword: 'revit lt', total: 1 } ]

Look that data is not longer the same, on the mongo result it shows in the hour attribute 0, 14 and 1 which does not appear  on result 2 ( mingo ) and  also keywords are not the same.
******* Anyway!
Both results are correct! It is because the algorithm used on mongo vs mingo, I get to that conclusion because I remove the limit clause on the query:
$ node test3.js 
Mongo result!******
[ { total: 3, hour: 5, keyword: 'autocad' },
  { total: 2, hour: 12, keyword: 'autocad' },
  { total: 1, hour: 0, keyword: 'autocad lt 2015' },
  { total: 1, hour: 6, keyword: 'autocad' },
  { total: 1, hour: 14, keyword: 'autocad' },
  { total: 1, hour: 0, keyword: 'autocad light' },
  { total: 1, hour: 7, keyword: 'autocad' },
  { total: 1, hour: 12, keyword: 'revit lt' },
  { total: 1, hour: 11, keyword: 'autocad' },
  { total: 1, hour: 10, keyword: 'autocad' },
  { total: 1,
    hour: 6,
    keyword: 'auto desk auto cad light software' },
  { total: 1, hour: 1, keyword: 'autodesk autocad lt mac' },
  { total: 1, hour: 4, keyword: 'autocad' },
  { total: 1, hour: 4, keyword: 'autodesk autocad lt' },
  { total: 1, hour: 3, keyword: 'autodesk autocad lt mac' },
  { total: 1, hour: 3, keyword: 'autocad' },
  { total: 1, hour: 1, keyword: 'autocad lt 2015' },
  { total: 1, hour: 15, keyword: 'autocad' },
  { total: 1, hour: 8, keyword: 'autocad' } ]
Mingo result!$$$$$
[ { hour: 5, keyword: 'autocad', total: 3 },
  { hour: 12, keyword: 'autocad', total: 2 },
  { hour: 10, keyword: 'autocad', total: 1 },
  { hour: 11, keyword: 'autocad', total: 1 },
  { hour: 12, keyword: 'revit lt', total: 1 },
  { hour: 14, keyword: 'autocad', total: 1 },
  { hour: 15, keyword: 'autocad', total: 1 },
  { hour: 0, keyword: 'autocad lt 2015', total: 1 },
  { hour: 0, keyword: 'autocad light', total: 1 },
  { hour: 1, keyword: 'autocad lt 2015', total: 1 },
  { hour: 1, keyword: 'autodesk autocad lt mac', total: 1 },
  { hour: 3, keyword: 'autocad', total: 1 },
  { hour: 3, keyword: 'autodesk autocad lt mac', total: 1 },
  { hour: 4, keyword: 'autocad', total: 1 },
  { hour: 4, keyword: 'autodesk autocad lt', total: 1 },
  { hour: 6, keyword: 'autocad', total: 1 },
  { hour: 6,
    keyword: 'auto desk auto cad light software',
    total: 1 },
  { hour: 7, keyword: 'autocad', total: 1 },
  { hour: 8, keyword: 'autocad', total: 1 } ]

Boom! Data are the same!! So my apologies because I didn't not consider this before, thanks for your tool, keep moving forward :+1: 

Thanks
Robert Baron
