### ISSUE TITLE
mingo vs sift.js

### ISSUE THREAD

**Issue by gajus** [kofrasa/mingo#170]
I could not find any comparisons.

Since both projects are actively maintained, I think many would love to know the perspective of both authors. Tagging @crcn.

What are the main differences (performance, use case, etc)?

**Comment by kofrasa** [comment]
I have not used [sift](https://www.npmjs.com/package/sift) myself so cannot provide a well informed comparison. Both projects advertise as providing MongoDB queries in Javascript so I think the goals are similar. 

From the project page, what stands out to me between the two is feature completeness. `mingo` aims to bring the full  MongoDB experience (i.e. filtering, evaluation, aggregation, and transformation) to the browser whereas `sift` seems to focus only on the filtering.

Both projects support tree-shaking to include only used features at build time so size may be similar. If you need a query alternative to filter collections, both libraries will do the job and the choice comes down the developer's API preference. To do more than filtering, I think `mingo` would be appropriate.

Feel free to reopen with new comments.
