### ISSUE TITLE
$or and $elementMatch operator producing error

### ISSUE THREAD

**Issue by caritasverein** [kofrasa/mingo#178]
First of all - thank you for the hard work everyone put into mingo!

As i used it for our latest project, i came across this issue. When i use `$elemMatch` and an operator like `$or` in the context you see below, it will fail if i use the `$or` operator first. Please have a look at my example:

```js
import mingo from "mingo";

const query_elemMatch_or = {
  array: {
    $elemMatch: {
      $or: [
        { thing: "A", number: { $gt: 200 } },
        { thing: "B", number: { $lt: 100 } }
      ]
    }
  }
};

const query_or_elemMatch = {
  array: {
    $or: [
      { $elemMatch: { thing: "A", number: { $gt: 200 } } },
      { $elemMatch: { thing: "B", number: { $lt: 100 } } }
    ]
  }
};

const example = [
  {
    array: [
      { number: 300, thing: "A" },
      { number: 400, thing: "B" }
    ]
  }
];

const working_example = new mingo.Query(query_elemMatch_or).find(example).all();
console.log("Working example", JSON.stringify(working_example));

try {
  new mingo.Query(query_or_elemMatch).find(example).all();
} catch (err) {
  console.log("Failing example", err);
}
```

The output will be as following:

```
Working example [{"array":[{"number":300,"thing":"A"},{"number":400,"thing":"B"}]}] 

Failing example 
Error: unknown top level operator: $elemMatch
    at Object.assert (https://3prqj.csb.app/node_modules/mingo/util.js:61:15)
    at Query._compile (https://3prqj.csb.app/node_modules/mingo/query.js:37:24)
    at new Query (https://3prqj.csb.app/node_modules/mingo/query.js:19:14)
    at eval (https://3prqj.csb.app/node_modules/mingo/operators/query/logical/or.js:16:54)
    at Array.map (<anonymous>)
    at $or (https://3prqj.csb.app/node_modules/mingo/operators/query/logical/or.js:16:25)
    at Query._processOperator (https://3prqj.csb.app/node_modules/mingo/query.js:51:18)
    at Query._compile (https://3prqj.csb.app/node_modules/mingo/query.js:40:26)
    at new Query (https://3prqj.csb.app/node_modules/mingo/query.js:19:14)
    at evaluate (https://3prqj.csb.app/src/index.js:31:3)
    [...]
```

You can use this codesandbox to see this issue in action: https://codesandbox.io/s/confident-shannon-u3w28

Maybe this issue is related to this merge request https://github.com/kofrasa/mingo/pull/164 and/or this issue https://github.com/kofrasa/mingo/issues/163.

Can you take a closer look to this?

**Comment by kofrasa** [comment]
Hi @caritasverein,

Thanks for reporting this issue and for using this libary.

First I would like to as if you have tested whether the query `query_or_elemMatch` is valid in MongoDB?

Many of the semantics in `mingo` are implemented from experimentally testing against MongoDB queries and not following an existing spec so some query constructions may legitimately not be supported.

**Comment by kofrasa** [comment]
I just confirmed the behaviour on MongoDB. The second query `query_or_elemMatch` in indeed invalid. See below

### MongoDB v4.4.5
```
> db.test.find({
...   array: {
...     $or: [
...       { $elemMatch: { thing: "A", number: { $gt: 200 } } },
...       { $elemMatch: { thing: "B", number: { $lt: 100 } } }
...     ]
...   }
... })
Error: error: {
	"ok" : 0,
	"errmsg" : "unknown operator: $or",
	"code" : 2,
	"codeName" : "BadValue"
}
```

The `$or` operator cannot be nested under a field expression. The error from `mingo` is somewhat misleading and a side-effect of possibly another rule being violated and a generic error message thrown in that case.
