### ISSUE TITLE
$filter does not have collection as context

### ISSUE THREAD

**Issue by MattIPv4** [kofrasa/mingo#187]
👋 I don't explicitly see the Mongo docs confirming expected behaviour either way, but when using this I noticed that expressions evaluated as `cond` in `$filter` only have the variable from `as` in the collection context, and not the wider parent context?

https://github.com/kofrasa/mingo/blob/8aaa4803cceff0261484dddc044516edefdf48d2/src/operators/expression/array/filter.ts#L24-L27

Should this be initialising `tempObj` as a deep clone of `obj` before injecting the temp variable from `as`? Or even just mutating `obj` with the temp var?

I've been using map as a workaround to this, mapping the extra items from the parent collection context into my array and passing that into the input of filter, as it seems `$map` does use the full collection context when evaluating each item:

https://github.com/kofrasa/mingo/blob/8aaa4803cceff0261484dddc044516edefdf48d2/src/operators/expression/array/map.ts#L33-L34

**Comment by kofrasa** [comment]
Thanks for reporting this @MattIPv4 . As you noted that is not specified but a quick test in the MongoDB shell suggests the entire object context should exist.

Using the collection

```
> db.test.find()
{ "_id" : 1, "pad" : 5, "quizzes" : [ 5, 6, 7 ] }
{ "_id" : 2, "pad" : 4, "quizzes" : [ ] }
{ "_id" : 3, "pad" : 3, "quizzes" : [ 3, 8, 9 ] }
```

**$filter example**
```
> db.test.aggregate(   [
...       { $project:
...          { adjustedGrades:
...             {
...               $map:
...                  {
...                    input: "$quizzes",
...                    as: "grade",
...                    in: { $add: [ "$$grade", "$pad", 2 ] }
...                  }
...             }
...          }
...       }
...    ])
{ "_id" : 1, "adjustedGrades" : [ 12, 13, 14 ] }
{ "_id" : 2, "adjustedGrades" : [ ] }
{ "_id" : 3, "adjustedGrades" : [ 8, 13, 14 ] }
```

**$map example**
```
> db.test.aggregate([
...   { $project:
...       { adjustedGrades:
...         {
...           $filter: {
...             input: [ 1, 2, 3, 4, 5, 10],
...             as: "num",
...             cond: { $gte: [ "$$num", "$pad" ] }
...           }
...         }
...       }
...   }
... ]
... )
{ "_id" : 1, "adjustedGrades" : [ 5, 10 ] }
{ "_id" : 2, "adjustedGrades" : [ 4, 5, 10 ] }
{ "_id" : 3, "adjustedGrades" : [ 3, 4, 5, 10 ] }
```

In that regard `$filter` should be updated to be consistent with the `$map` implementation. Feel free to send a PR. Please include some tests when you do. 

Note that the pipeline operators already take care of cloning the object before passing it down to the expressions.
