### ISSUE TITLE
Nested Arrays

### ISSUE THREAD

**Issue by gotdan** [kofrasa/mingo#19]
Hi,

It looks like mingo doesn't correctly return values in nested arrays. For example, with this data set:

``` javascript
var data = [{
    key0: [{
        key1: [ {key2: "value2"} ],
        key1a: {key2a: "value2a"}
    }]
}];
```

The expression `{"key0.key1a.key2a": "value2a"}` returns the object, while the expression `{"key0.key1.key2": "value2"}` returns an empty array. Am I constructing the query wrong?

Thanks,
Dan

**Comment by kofrasa** [comment]
I think your query should be valid but I would have to confirm it with MongoDB behaviour. I think I remember there were some limitations with the level of nesting with array queries but they are on  version 3.0 now so things might work differently.

Anyway an equally viable alternative for what you are trying to achieve would be to use the `$elemMatch` operator such as `{"key0.key1": {"$elemMatch": {key2: "value2"}}}`

**Comment by gotdan** [comment]
Thanks - I’m not sure $elemMatch will work with this dataset though, since in some cases the value will be an object and and in some the same key will have an array of objects as the value (depending on how many children there are).  I don’t have control over the data format, so one of the nice things about the mongo dot notation is that the same query should work in both cases.  

Do you know if there is a way to use $elemMatch or another operator to handle this use case?

**Comment by kofrasa** [comment]
In that case you could use an `$or` operator (a bit of a hack i guess) :). 

```
{$or: [
  {"key0.key1": {"$elemMatch": {key2: "value2"}}},
  {"key0.key1.key2": "value2"}
]}
```
I will look into the bug soon.

**Comment by kofrasa** [comment]
Just release 0.6.1 that fixes the issue.

**Comment by gotdan** [comment]
Thanks! That was faster than I could implement a work around :).
