### ISSUE TITLE
Regexes are not supported in $all queries

### ISSUE THREAD

**Issue by pypmannetjies** [kofrasa/mingo#190]
It appears that RegExp are not supported in [`$all` queries](https://docs.mongodb.com/manual/reference/operator/query/all/) when using Mingo, [but they are in MongoDB](https://docs.mongodb.com/manual/reference/operator/query/regex/)

Opened a PR with a new test to show the issue: https://github.com/kofrasa/mingo/pull/189

**Comment by kofrasa** [comment]
Thanks for opening an issue. 

I interpret the above as saying that; regexes are supported when using the `$all` operator in `mingo` but not in `MongoDB`. This means the behaviour in `mingo` is not correct and your PR confirms that is the case.

Unfortunately, this library is not implemented according to a spec, and such inconsistencies do exists. This is one of such that cannot be fix since doing so can break existing users depending on the behaviour. Also, it seems desirable that regexes work under `$all` so I inclined to believe users will prefer this behaviour.

I will add a section to the readme to document such differences in a future update.

**Comment by pypmannetjies** [comment]
> Thanks for opening an issue.
> 
> I interpret the above as saying that; regexes are supported when using the `$all` operator in `mingo` but not in `MongoDB`. This means the behaviour in `mingo` is not correct and your PR confirms that is the case.
> 
> Unfortunately, this library is not implemented according to a spec, and such inconsistencies do exists. This is one of such that cannot be fix since doing so can break existing users depending on the behaviour. Also, it seems desirable that regexes work under `$all` so I inclined to believe users will prefer this behaviour.
> 
> I will add a section to the readme to document such differences in a future update.

Hmmm no I am reporting that Regexes are NOT supported when using the `$all` operator in `mingo`, but they ARE supported in `MongoDB`. So I assumed this is an error in Mingo that could be fixed.

**Comment by kofrasa** [comment]
The test in https://github.com/kofrasa/mingo/pull/189 is passing which suggest regexes are supported in `$all`.

Can you provide an example from MongoDB that would not work in `mingo`?

**Comment by pypmannetjies** [comment]
> The test in #189 is passing which suggest regexes are supported in `$all`.
> 
> Can you provide an example from MongoDB that would not work in `mingo`?

Apologies but I can't see where the tests passed in that PR, I see a https://lgtm.com/projects/g/kofrasa/mingo/rev/pr-5c21c72550d61fb694e6053b90023e3910298c8d LGTM page but not where the tests are running. 

Locally, this test fails for me.

**Comment by kofrasa** [comment]
My bad, I wrongly assumed the status checks also includes the unit test execution status. I should set that up sometime.

I will mark this as a bug. Please feel free to send a PR. Will be very much appreciated.

**Comment by pypmannetjies** [comment]
> My bad, I wrongly assumed the status checks also includes the unit test execution status. I should set that up sometime.
> 
> I will mark this as a bug. Please feel free to send a PR. Will be very much appreciated.

Thank you! I pushed a potential fix to [my PR](https://github.com/kofrasa/mingo/pull/189)

Added some additional tests, and they are passing fine. I'm not super familiar with this project so please LMK if this is not the right approach for the fix.
