### ISSUE TITLE
$setUnion is not upto spec

### ISSUE THREAD

**Issue by deviprsd** [kofrasa/mingo#192]
The behavior of set union is described on [mongo docs](https://docs.mongodb.com/manual/reference/operator/aggregation/setUnion/#mongodb-expression-exp.-setUnion) such as this 

> $setUnion performs set operation on arrays, treating arrays as sets. If an array contains duplicate entries, 
$setUnion ignores the duplicate entries. $setUnion ignores the order of the elements.

> $setUnion *filters out duplicates in its result to output an array that contain only unique entries*. The order 
of the elements in the output array is unspecified.

The issue being here is that the resulting array is not being treated as a set as mentioned by the behavior above, so a test case such as 

```ts
[ "a", "b", "a" ], [ "b", "a" ] // should return ["a", "b"] but returns ["a", "b", "a"]
```

A quick test change on your tests proved this issue, a similar test case is shown in this section https://docs.mongodb.com/manual/reference/operator/aggregation/setUnion/#behavior

```
Expected: [ { A: [ 'red', 'blue', 'red' ], B: [ 'red', 'blue' ], allvalues: [ 'red', 'blue' ] } ]
Actual: [ { A: [ 'red', 'blue', 'red' ], B: [ 'red', 'blue' ], allValues: [ 'red', 'blue', 'red' ] } ]
```

A super quick fix in https://github.com/kofrasa/mingo/blob/30ff02aa3d41541685255ed6bc51431d1e8a650c/src/util.ts#L316-L322 would be

```ts
return Array.from(new Set<unknown>(result))
```

But that is added preformation for doing conversion from Array to Set to Array...

**Comment by kofrasa** [comment]
Thanks for raising the issue and for the recommended fix using [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set).

I do accept PRs if you want to give it a bash.
