### ISSUE TITLE
Custom top-level operators

### ISSUE THREAD

**Issue by bjornolofandersson** [kofrasa/mingo#201]
I'm trying to implement my own $jsonSchema operator for mingo and I'm running into some issues since it is a top-level query operator.

Seems like mingo puts on a restriction for these by only allowing certain pre-defined ones:

```typescript
      if ("$where" === field) {
        whereOperator = { field: field, expr: expr };
      } else if ("$expr" === field) {
        this.processOperator(field, field, expr);
      } else if (inArray(["$and", "$or", "$nor"], field)) {
        this.processOperator(field, field, expr);
      } else {
        // normalize expression
        assert(!isOperator(field), `unknown top level operator: ${field}`);
        for (const [operator, val] of Object.entries(normalize(expr))) {
          this.processOperator(field, operator, val);
        }
      }
```

I'm getting "unknown top level operator: $jsonSchema". Is there a way to lift this restriction?

**Comment by kofrasa** [comment]
Thanks for opening this issue @bjornolofandersson. 

The only restriction to add any operator is that it must not be already implemented in the library.

I have not gotten around to implementing [$jsonSchema](https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/#mongodb-query-op.-jsonSchema) yet, so you can implement it as a custom operator and then register it using [addOperators](https://github.com/kofrasa/mingo/blob/f5caed962bebf338984fb770429a27e5ac943a27/src/core.ts#L190)  with [OperatorType.QUERY](https://github.com/kofrasa/mingo/blob/f5caed962bebf338984fb770429a27e5ac943a27/src/core.ts#L74).

If your implementation is exhaustive and has testing, I will appreciate a PR that adds it directly to the library as part of the [evaluation](https://github.com/kofrasa/mingo/tree/master/src/operators/query/evaluation) operators.

Hope that helps.

**Comment by bjornolofandersson** [comment]
Hi!

Thank you for your quick reply! I was originally thinking of adding the $jsonSchema operator as an external thing, but now that you mentioned it, it would actually be even better to try to get it into the mingo code base itself.

I'll have a go at it and will keep you updated on the progress. The $jsonSchema operator would require a third party library to be included so I will see what is fitting.

However, aside from that, I still think there is a potential issue here for anyone wanting to add an external top-level operator that is not recognised internally by the library, given the code snippet I provided above. Would be nice to have a way around that restriction.

Best regards,
Björn

**Comment by bjornolofandersson** [comment]
Actually, at a closer inspection, I'm probably wrong about there being a restriction. Perhaps I just failed to add my operator properly. I'll give it another shot tomorrow.

Thanks again!

**Comment by kofrasa** [comment]
> Hi!
> 
> Thank you for your quick reply! I was originally thinking of adding the $jsonSchema operator as an external thing, but now that you mentioned it, it would actually be even better to try to get it into the mingo code base itself.
> 
> I'll have a go at it and will keep you updated on the progress. The $jsonSchema operator would require a third party library to be included so I will see what is fitting.
> 
> However, aside from that, I still think there is a potential issue here for anyone wanting to add an external top-level operator that is not recognised internally by the library, given the code snippet I provided above. Would be nice to have a way around that restriction.
> 
> Best regards, Björn

If you are adding a custom operator then a dependency is fine. For adding to mingo core, the operator must be implemented directly in the library. This is the only constraint to adding code to this library. I have found that many of the operators are not that complicated to merit a dependency and schema validation likely falls into that category. 

Another approach for your use-case, is to load the `$where` operator and then write a custom function to perform the schema validation  using your favourite JSON schema library.

**Comment by kofrasa** [comment]
> Actually, at a closer inspection, I'm probably wrong about there being a restriction. Perhaps I just failed to add my operator properly. I'll give it another shot tomorrow.
> 
> Thanks again!

Actually you were correct about the restriction. That applies to query operators that act on the entire document and not specific fields. I am adding support for `$jsonSchema` in the next version. Given the nuances of the operator and compatibility difference between MongoDB's format and other popular ones in the wild, I will leave the option of the schema validator to use to the user. That will basically allow you to just implement the validator itself using whatever format you prefer whilst getting the operator for free.
