### ISSUE TITLE
Aggregation pipeline - $min on fields with type string not working

### ISSUE THREAD

**Issue by vdininski** [kofrasa/mingo#21]
If you try to do a `$min` aggregation on a string field in a collection you receive `Infinity` instead of the actual result. I still haven't tried, but I think that `$max` would work the same way. The issue is that `_.min` returns `Ifinity` when using strings.

**Comment by vdininski** [comment]
Also `$avg` returns `NaN` if there is a document where the field is undefined

**Comment by kofrasa** [comment]
I have been working on refactoring the aggregation framework into a library of its own. This will make the core of mingo a bit smaller and provide the extra features on demand. Nonetheless I will get some tests going for these issues soon

**Comment by kofrasa** [comment]
I also welcome pull requests. Just rebase changes to one commit and add the corresponding tests

**Comment by kofrasa** [comment]
Fixed in release [0.6.3](https://github.com/kofrasa/mingo/releases/tag/0.6.3)
