### ISSUE TITLE
Error: unknown operator $numberDecimal

### ISSUE THREAD

**Issue by mylawacad** [kofrasa/mingo#214]
Hi, could you please let me know if mingo is capable to compare Decimal128 data type please?

**Comment by kofrasa** [comment]
Can you provide an example of what you asking?

Mingo implements all the [type](https://docs.mongodb.com/manual/reference/operator/aggregation/#type-expression-operators) operators offered by MongoDB that client-side Javascript can natively support.

**Comment by kofrasa** [comment]
Resolving this issue. Please refer to MongoDB documentation for how to use the type operators.
