### ISSUE TITLE
Export and Import feature

### ISSUE THREAD

**Issue by asgaraliyev** [kofrasa/mingo#216]
Hello guys.Is there any feature like exporting and importing data into databases by once in mingo software? I coudnt find

**Comment by kofrasa** [comment]
This library is used for querying, manipulating, or aggregating results from a sequence of complexly structured JSON objects in memory. It does not provide a database of any kind for storing those objects nor an interface for updating the objects. 

For the actual database please consider using the [MongoDB](https://docs.mongodb.com/) product which also ships with various data [import and export](https://docs.mongodb.com/database-tools/mongoimport/) tools.
