### ISSUE TITLE
`replaceOne` and `replaceAll` missing from package (v5.1.0)

### ISSUE THREAD

**Issue by cezarcarvalhaes** [kofrasa/mingo#220]
Currently getting `operator '$replaceOne' is not registered` when trying to access this method. I upgraded to the latest (v5.1.0) and the methods are still missing.  I manually checked the package contents in `operators/expressions/string` and these methods are missing.

The CHANGELOG.md says there were added on 12/05/2021.

**Comment by kofrasa** [comment]
That is strange. The operators are implemented since `5.0.0`. I just  installed `5.1.0` and you are correct that the files are missing. 

Must have been some publishing errors from the local file system. Expect an update shortly.

**Comment by kofrasa** [comment]
Tracked down the bug to `5.0.0` which means none of the new operators added in `5.0.0` and `5.1.0` were uploaded.

**Comment by kofrasa** [comment]
Fixed in [6.0.0](https://www.npmjs.com/package/mingo/v/6.0.0). Please verify and resolve issue.

**Comment by cezarcarvalhaes** [comment]
Just grabbed them. Looks great, thanks!
