### ISSUE TITLE
importing assert from console in dateToString causes usage with Webpack v5 to break

### ISSUE THREAD

**Issue by cezarcarvalhaes** [kofrasa/mingo#225]
Using mingo v6+ in an app built with webpack throws an error: `Module not found: Error: Can't resolve 'console' in...`. 

Webpack also includes the message: `BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.`

This is caused by importing assert from console in `dateToString.ts` and can be fixed by simply calling `console.assert` directly. A pull request for this is coming shortly.

**Comment by kofrasa** [comment]
Thanks @cezarcarvalhaes. Actually the code should be calling [assert](https://github.com/kofrasa/mingo/blob/master/src/util.ts#L56) from the `util` module.
