### ISSUE TITLE
Incorrect behavior with dotted path query on nested arrays

### ISSUE THREAD

**Issue by cmlenz** [kofrasa/mingo#238]
I ran into the following query working on the MongoDB playground, but not working in Mingo:

```js
  const query = new Query({'children.children.flags': 'foobar'});
  const result = query.test({
    "children": [
      {
        "children": [
          {
            "flags": ["foobar"],
          },
        ],
      },
      {
        "children": [
          {
            "flags": [],
          },
        ],
      },
    ],
  });

  expect(result).toBe(true); // ❌ fails
```

Here's the link to the playground: https://mongoplayground.net/p/NTqxvjkqAEh. Here I am getting the expected result.

With Mingo, the query does not match.

When I remove one level of nesting and adjust the query, the test passes:

```js
  const query = new Query({'children.flags': 'foobar'});
  const result = query.test({
    "children": [
      {
        "flags": ["foobar"],
      },
      {
        "flags": [],
      },
    ],
  });

  expect(result).toBe(true); // ✅ works
```

It also matches when I remove the second child!

```js
  const query = new Query({'children.grandchildren.flags': 'foobar'});
  const result = query.test({
    "children": [
      {
        "grandchildren": [
          {
            "flags": [
              "foobar",
            ],
          },
        ],
      },
    ],
  });

  expect(result).toBe(true); // ✅ works
```

Is this a bug or am I misunderstanding / misconfiguring?

**Comment by kofrasa** [comment]
Thanks for the bug report. We are not correctly handling deeply nested array comparisons [here](https://github.com/kofrasa/mingo/blob/master/src/operators/_predicates.ts#L94). The array should be flattened to the depth of the selector before comparing.

**Comment by cmlenz** [comment]
Wow, that was quick. It works now. Thanks a lot!

**Comment by kofrasa** [comment]
You are welcome.
