### ISSUE TITLE
Require cycle react-native

### ISSUE THREAD

**Issue by kmalakoff** [kofrasa/mingo#241]
When I use mingo@6.0.6 in a react-native project, it looks like they are checking for require cycles and there's 3 in mingo.

These are just warning so not affecting my project, but I wanted to let you know in case you'd like to remove these require cycles. 

```
LogBox.js:173 Require cycle: node_modules/mingo/operators/expression/index.js -> node_modules/mingo/operators/expression/date/index.js -> node_modules/mingo/operators/expression/date/dateSubtract.js -> node_modules/mingo/operators/expression/index.js

LogBox.js:173 Require cycle: node_modules/mingo/operators/expression/object/index.js -> node_modules/mingo/operators/expression/object/unsetField.js -> node_modules/mingo/operators/expression/object/index.js

LogBox.js:173 Require cycle: node_modules/mingo/operators/pipeline/index.js -> node_modules/mingo/operators/pipeline/setWindowFields.js -> node_modules/mingo/operators/pipeline/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

**Comment by kofrasa** [comment]
Thanks for the report @kmalakoff. It looks like these are bad imports likely from relying on auto-complete. 

https://github.com/kofrasa/mingo/blob/master/src/operators/expression/date/dateSubtract.ts#L5
https://github.com/kofrasa/mingo/blob/master/src/operators/expression/object/unsetField.ts#L5
https://github.com/kofrasa/mingo/blob/master/src/operators/pipeline/setWindowFields.ts#L14
