### ISSUE TITLE
addOperators replacement?

### ISSUE THREAD

**Issue by individual11** [kofrasa/mingo#254]
I see you dropped the `addOperators` function from core (some time ago, but I wasn't updating my local copy for testing, that's on me) in favor of customer operators like `$function`. I was hoping to add functionality to all mingo call, without having to always add `$function` inline to the aggregation pipeline itself. Is that still possible?

My use case is I want to have a few basic functions like converting a number to currency. I would want anyone on my team that needs it to not have to write it every time in every pipeline. Thoughts?

**Comment by individual11** [comment]
I was able to answer my own question. It looks like with a mild configuration change to how the old `addOperators` work, I could easily use the `useOperators` function to add new functionality. Would you want that in the wiki, or is that something to be avoided?

**Comment by kofrasa** [comment]
I will update the wiki. Unfortunately that page is a bit stale.

**Comment by individual11** [comment]
Happy to do a PR to it if using `useOperators` to bring in custom operators is the intent.

**Comment by kofrasa** [comment]
Updated the [wiki](https://github.com/kofrasa/mingo/wiki/Custom-Operators) to reflect `useOperator`. Thanks
