### ISSUE TITLE
dateToParts timezone returning incorrect hour

### ISSUE THREAD

**Issue by cezarcarvalhaes** [kofrasa/mingo#256]
When using `$dateToParts` and passing in a UTC offset to the timezone parameter, resulting hour value is a head by 10 hours when passing in $$NOW value and timezone as `'-05:00'`.

Here's an example:

```javascript
[
  {
    $addFields: {
      localTime: {
        $dateToParts: {
          date: '$$NOW',
          timezone: '-05:00',
          iso8601: true,
        },
      },
    },
  },
]
```

When I ran this at 10am (EST), I received `hour: 19`. I expected to receive `hour: 9`. Here's a quick [mongo playground](https://mongoplayground.net/p/cB1yQuIsza0) reproduction of the query that returns the expected values.

I currently have a workaround to this that is working fine, but wanted to draw attention to this.
 
---

WORKAROUND: parse `$$NOW` using `$dateToString` with timezone, before passing to `$dateToParts`:

```javascript
{
  $addFields: {
    localTime: {
      $dateToParts: {
        date: {
          $dateToString: {
            date: '$$NOW',
            timezone: '-05:00',
          },
        },
      },
    },
  },
}
```

**Comment by kofrasa** [comment]
Hi @cezarcarvalhaes , thanks for the bug report. Seems like a bug due to a bad test code.
