### ISSUE TITLE
Add support for $topN (aggregation)

### ISSUE THREAD

**Issue by kofrasa** [kofrasa/mingo#266]
Implement accumulator operator [$topN](https://www.mongodb.com/docs/manual/reference/operator/aggregation/topN/#mongodb-group-grp.-topN).

**Comment by cristian-moreno-ruiz** [comment]
Any news, ETA? 🙏 

Thanks!

**Comment by kofrasa** [comment]
Happy to accept a PR. Might be a while before I get to the new operators from Mongo `5.2`.

**Comment by kofrasa** [comment]
Closed in 053db0252998a945b62065fd4ca7cfd1a4f9c79a
