### ISSUE TITLE
Possible breaking error in 6.1.1 `dateFromParts`

### ISSUE THREAD

**Issue by individual11** [kofrasa/mingo#274]
I'm still investigating on my side, but an internal function to the file operators/expression/date/dateFromParts.ts `dateFromPartsFixtures` (which doesn't seem to be getting called from what I can tell at first glance) is causing an import to occur in the js file looking for the parent src folder. At least in my create-react-app that's using it, it's crashing. It looks like it was added in the 6.1.1 release 2 days ago (and was also removed from the test files).

Will update here if I find more info out, but wanted to bring it up quickly.

**Comment by kofrasa** [comment]
Looks like a bad refactor. That function `dateFromPartsFixtures` should not be there at all.
