### ISSUE TITLE
Es6 Module build

### ISSUE THREAD

**Issue by pubkey** [kofrasa/mingo#294]
Hi @kofrasa 
Thank you for that wonderful package. I am using it inside of RxDB and it works great.

I just have a small problem:
At the moment, there is no es6 module build contained in the package.
This causes the webpack tree shaking to bailout
![mingo](https://user-images.githubusercontent.com/8926560/210445203-a6a2ee79-5040-47fe-82b8-aac7543dd417.png)

Could we add the es6 module syntax (import/export) as typescript build output?

**Comment by kofrasa** [comment]
Hi @pubkey, thanks for using the library and finding it useful. Will look into this. Also happy to accept a PR.
