### ISSUE TITLE
Issues with $let since 6.2.0

### ISSUE THREAD

**Issue by abarthen** [kofrasa/mingo#302]
When trying to upgrade from 6.1.3 I am experiencing issues with queries that should work. $let seems to be one source of this, though apparently not the only one - replacing the 6.2.X version of $let with the 6.1.3 version prevents the query from crashing but the result is still wrong.

I have this example query which works in the mongo playground and also worked prior to 6.2.0:
https://mongoplayground.net/p/Yf2QrwCX7Sf

If I log what `let.js` does I get `{e: "t"}` as `variables`, which makes sense since the first element in the list I check is the string `"string"`, so the element at index 1 is "t". But I then get the error `Use of undefined variable: e` and execution stops.

Using the code from 6.1.3 for `$let` fixes this and the result of `$let` is correct but the endresult is still wrong (no element gets returned), so there are apparently more issues elsewhere.

**Comment by kofrasa** [comment]
Thanks for the report @abarthen. I think it was introduced in the refactor to separate variables from the actual document for processing.
