### ISSUE TITLE
$filter "truthy" condition returns incorrect results

### ISSUE THREAD

**Issue by gak10100** [kofrasa/mingo#320]
When using $filter with a "truthy" condition it filters out all results.

```
const result = aggregate(
	[
		{
			urls: [
				'http://google.com',
				'http://msn.com',
				null
			]
		}
	],
	[
		{
			"$project": {
				"urls": {
					"$filter" : {
						"input" : "$urls",
						"as" : "url",
						"cond" : "$$url"
					}
				}
			}
		}
	]
);

console.log(result[0]);
```
Expected Result
```
{ urls: [ 'http://google.com', 'http://msn.com'] }
```
Actual Result
```
{ urls: [] }
```

**Comment by gak10100** [comment]
Please note that mongo filters out null and false but does NOT filter out empty string

**Comment by kofrasa** [comment]
Thanks for reporting this [bug](https://github.com/kofrasa/mingo/blob/master/src/operators/expression/array/filter.ts#L33). Need to improve [testing](https://github.com/kofrasa/mingo/blob/master/test/operators/expression/array/filter.test.ts) across a number of operators given the [examples](https://www.mongodb.com/docs/manual/reference/operator/aggregation/filter/) aren't always sufficient.

Feel free to send a PR.

**Comment by gak10100** [comment]
It appears $cond is inconsistent with mongo on empty string. I prefer mingo's implementation but for consistency.

```
{
	"$project": {
		"emptyString": { $cond: ['', true, false] },
		"null": { $cond: [null, true, false] },
		"undefined": { $cond: [undefined, true, false] },
		"-1": { $cond: [-1, true, false] },
		"0": { $cond: [0, true, false] },
		"1": { $cond: [1, true, false] }
	}
}
```

Mingo
```
{
  '0': false,
  '1': true,
  string: true,
  emptyString: false,
  null: false,
  undefined: false,
  '-1': true
}
```

Mongo
```
{
  '0': false,
  '1': true,
  string: true,
  emptyString: true,
  null: false,
  undefined: false,
  '-1': true
}
```

**Comment by kofrasa** [comment]
> It appears $cond is inconsistent with mongo on empty string. I prefer mingo's implementation but for consistency.
> 
> ```
> {
> 	"$project": {
> 		"emptyString": { $cond: ['', true, false] },
> 		"null": { $cond: [null, true, false] },
> 		"undefined": { $cond: [undefined, true, false] },
> 		"-1": { $cond: [-1, true, false] },
> 		"0": { $cond: [0, true, false] },
> 		"1": { $cond: [1, true, false] }
> 	}
> }
> ```
> 
> Mingo
> 
> ```
> {
>   '0': false,
>   '1': true,
>   string: true,
>   emptyString: false,
>   null: false,
>   undefined: false,
>   '-1': true
> }
> ```
> 
> Mongo
> 
> ```
> {
>   '0': false,
>   '1': true,
>   string: true,
>   emptyString: true,
>   null: false,
>   undefined: false,
>   '-1': true
> }
> ```

Will address all remaining cases in https://github.com/kofrasa/mingo/issues/321.
