### ISSUE TITLE
Question: Why has the generic type for Cursor been removed?

### ISSUE THREAD

**Issue by m0rtalis** [kofrasa/mingo#357]
Hi,
I'm in the process of upgrading from version 2.5.3 to 6.4.3 and noticed that the [generic type from the Cursor class](https://github.com/kofrasa/mingo/blob/2.5.3/index.d.ts#L240-L249) has been removed and the [current version](https://github.com/kofrasa/mingo/blob/main/src/cursor.ts) only returns `unknown` for the values instead.

For me it seems like the library became, at least for the consumer, less typesafe with the switch to Typescript.
Is there a particular reason for this change?

**Comment by kofrasa** [comment]
I don't really recall the motivation but I would guess it was done to encourage explicit casting. We can certainly  restore the generic type and default to `unknown`.

**Comment by kofrasa** [comment]
Resolved in `mingo@6.4.4`
