### ISSUE TITLE
Documentation: what's a collection?

### ISSUE THREAD

**Issue by SachaG** [kofrasa/mingo#37]
This might seem obvious, but the documentation uses the term `collection` everywhere without ever giving an example of what a collection should look like. I think having a quick illustration of what you mean (array? JS object? something else?) would be useful.

**Comment by kofrasa** [comment]
Thanks for the  question Sacha. I see how this may not be obvious although I thought it was implied given this library mimics MongoDB.

A collection is for the most part an `Array` of elements of type `Object`. This may not be strictly validated in some parts of the code depending on the type of query being executed and may lead to unexpected results. Such behaviour should definitely be reported as a bug.

I will consider adding better documentation to address this problem.

I appreciate you calling this out.

Thanks.

**Comment by SachaG** [comment]
Thanks! I did figure it out eventually but I thought the ambiguity could be avoided :)
