### ISSUE TITLE
updateObject does not work for array of objects with the $pull operator

### ISSUE THREAD

**Issue by nkemcels** [kofrasa/mingo#373]
Hello @kofrasa, first, thanks for building and maintaining this powerful library.

I've integrated the newly released and long awaited `updateObject` from the `mingo/updater` module and everything has been working really well. There's however one use case which I think is missing.

When I run the `updateObject` function
```js
updateObject(obj, {
    $pull: { "owner": { $in: ["owner1"] } },
});
```

on this object,

```js
const obj = {
    title: "Tobi",
    author: "Brian",
    date: "2023-09-30T15:45:44.097Z",
    owners: ["owner1", "owner2"],
    comments: [
        {
            _id: "comment1",
            date: null,
            body: "been there",
        },
        {
            _id: "comment2",
            date: null,
            body: "done that",
        },
    ],
    _id: "651842a8b50c196f074197ce",
};
```
the `owners` array is properly filtered and the `"owner1"` is removed from that `owners` array as expected.
However, when I run the function on the `comments` array as below

```js
updateObject(obj, {
    $pull: { "comments._id": { $in: ["comment1"] } },
});
```
It does not filter out the comment entry with `_id` of `"comment1"`. In fact the array stays the same and nothing happens.

I tried investigating the library's code to see what the issue could be and here are my two cents.
The `walk` function called in the `applyUpdate` function here on **line 87** isn't resolving the array when the selector is `comments._id` and hence the `g` callback isn't invoked
https://github.com/kofrasa/mingo/blob/3a929661f17f2d0f490d0d95b22e6b252908e8b8/src/operators/update/_internal.ts#L75-L102

How will things play out if a different `walk` function (maybe `walkForUpdater`) similar to the current is implemented with one tweak to it. When it meets the first array, (in this case `comments`), it returns it. If there are any remaining selectors, then we know that it is an array of objects. and the remaining selectors (`_id`) if any, would be used to get the value from the object item (`v`) here

https://github.com/kofrasa/mingo/blob/3a929661f17f2d0f490d0d95b22e6b252908e8b8/src/operators/update/pull.ts#L21

What do you think @kofrasa? I believe this is actually a common use case

**Comment by kofrasa** [comment]
Hi @nkemcels, first of all thanks for using library and also diving deep to investigate this issue. 

I will have to confirm if this behaviour is allowed within MongoDB nonetheless, I think we may be able to support it. Will take a closer look at your suggestion and respond soon.

**Comment by kofrasa** [comment]
I think your suggestion will work however a quick test shows that this is not actually supported in MongoDB. Tested on https://mongoplayground.net.

```
fail to run update: write exception: write errors: [Cannot use the part (_id) of (comments._id) to traverse the element ({comments: [ { _id: "comment1", date: null, body: "been there" }, { _id: "comment2", date: null, body: "done that" } ]})]
```

**Comment by kofrasa** [comment]
This seems specific to the operator itself. I think the different expressions is more than syntactic sugar from MongoDB point of view since `"comments.0"` does not always translate to `{ comments: { 0: <val>} }` or `{ comments: [{0: <v1>}, {0: <v2>}] }`. We can support the official expression which will be consistent with the expected semantics.

**Comment by kofrasa** [comment]
I still think it would be nice to support the dot-separated key syntax but I will leave that out for now until I have better understanding.

**Comment by kofrasa** [comment]
Thanks again for helping to improve this library. Unfortunately, the testing in this library is limited to examples provided on the MongoDB website so there are gaps here and there.

**Comment by nkemcels** [comment]
> This seems specific to the operator itself. I think the different expressions is more than syntactic sugar from MongoDB point of view since `"comments.0"` does not always translate to `{ comments: { 0: <val>} }` or `{ comments: [{0: <v1>}, {0: <v2>}] }`. We can support the official expression which will be consistent with the expected semantics.

Hmm... didn't think about the different possibilities with the dot-separated key syntax. Yeah, in that case it'll make sense to make it part of the library. But like you mentioned, for a start the official expression should do the trick for most of use cases.
