### ISSUE TITLE
$push with updateObject does not create the array if the fields does not exist

### ISSUE THREAD

**Issue by nkemcels** [kofrasa/mingo#384]
Hello @kofrasa, when I run this query on MongoDB, it works
```js
// input
// ---------
[
  {
    _id: "651842a8b50c196f074197ce",
    name: "Celsoppe"
  }
]

// query
// ----------
db.collection.update({},
{
  $push: {
    "attributes.scores.bar": {
      a: 1
    }
  }
})

// result/output
// -----------
[
  {
    "_id": "651842a8b50c196f074197ce",
    "attributes": {
      "scores": {
        "bar": [
          {
            "a": 1
          }
        ]
      }
    },
    "name": "Celsoppe"
  }
]
```

You can see that the `attributes.scores.bar` array doesn't exist but gets created with the `$push` operator. However, with `mingo`, that array must exist before the `$push` can go through.

**Comment by kofrasa** [comment]
Thanks for identifying this bug. The object graph is not built in realtime for the `$push` operator and many others so the full graph must exist. Will look into it.
