### ISSUE TITLE
Date comparison doesn't work with strings

### ISSUE THREAD

**Issue by SachaG** [kofrasa/mingo#39]
I was using a selector that filters based on dates: 

```
{
  "postedAt":{
    "$gte":"2017-01-04T15:00:00.000Z",
    "$lt":"2017-01-14T14:59:59.999Z"
  }
}
```

As far as I can tell, this doesn't work properly when the `postedAt` field contains date strings (the resulting cursor just came up empty), but it did work when I converted `postedAt` to date objects. 

Is this the expected behavior? Or am I missing something?

**Comment by kofrasa** [comment]
Hi @SachaG 

Mingo uses the default comparison operators in Javascript for value comparisons. The ISO-8601 date format is ordered by default and should compare properly.

I tested this on [runkit](https://runkit.com/npm/mingo) and also on MongoDB. The behaviour is as expected.

### Mingo Tests

```js
var Mingo = require("mingo");

var data = [
    {"id":1, "postedAt":"2017-01-04T15:00:00.000Z"},
    {"id":1, "postedAt":"2017-01-14T14:59:59.999Z"}
];

var res = Mingo.find(data, {
  "postedAt":{
    "$gte":"2017-01-04T15:00:00.000Z",
    "$lt":"2017-01-14T14:59:59.999Z"
  }
}).all();

console.log(JSON.stringify(res)); // "[{\"id\":1,\"postedAt\":\"2017-01-04T15:00:00.000Z\"}]"
```

### MongoDB Tests

```js
> db.test.find()
{ "_id" : ObjectId("587d9eef3361cf408b6784ab"), "postedAt" : "2017-01-04T15:00:00.000Z", "name" : 100 }
{ "_id" : ObjectId("587d9eff3361cf408b6784ac"), "postedAt" : "2017-01-14T14:59:59.999Z", "name" : 200 }
> db.test.find({
...   "postedAt":{
...     "$gte":"2017-01-04T15:00:00.000Z",
...     "$lt":"2017-01-14T14:59:59.999Z"
...   }
... })
{ "_id" : ObjectId("587d9eef3361cf408b6784ab"), "postedAt" : "2017-01-04T15:00:00.000Z", "name" : 100 }
```

Please can you provide the query you were trying to run?

**Comment by SachaG** [comment]
Hmm, I guess my issue is coming from something else then… let me test this out some more and I'll update you if I find out what it is.

**Comment by SachaG** [comment]
Oh ok, I think I got it. The issue didn't come from dates vs strings per se, it came from having different types. So when both the filter object and the collection documents use strings, or both use dates, it works. But when they have different types, it obviously stops working!
