### ISSUE TITLE
AWS SSO

### ISSUE THREAD

**Issue by MartinLoeper** [kofrasa/mingo#394]
I wonder if there is an option to authenticate via temporary credentials using AWS SSO? Can we pass env vars or the like? Manually inserting a temporary AWS Session Token everyday seems cumbersome.

**Comment by kofrasa** [comment]
@MartinLoeper  this library does not depend on any cloud service. Perhaps you are looking for a different project.

**Comment by MartinLoeper** [comment]
Stupid me, wrong mingo project. Sorry
