### ISSUE TITLE
Add a .get for dot notation on object.

### ISSUE THREAD

**Issue by jamesgibson14** [kofrasa/mingo#47]
Similar to https://www.npmjs.com/package/mongo-query#querygetobj-key

**Comment by kofrasa** [comment]
`Mingo` chooses not to expose the path resolution methods directly except to those writing custom operators. Nonetheless you can access them with `Mingo._internal()` if there is a real need.

**Comment by kofrasa** [comment]
This is already supported. https://github.com/kofrasa/mingo/blob/master/README.md
