### ISSUE TITLE
$where operator is not evaluated last

### ISSUE THREAD

**Issue by lackofbrilliance** [kofrasa/mingo#49]
The MongoDB documentation for the $where operator says that it is evaluated after all other operators:

"MongoDB will evaluate non-$where components of query before $where statements. If the non-$where statements match no documents, MongoDB will not perform any query evaluation using $where."

https://docs.mongodb.com/manual/reference/operator/query/where/

However, mingo does not evaluate $where last.

**Comment by kofrasa** [comment]
@lackofbrilliance  I appreciate the reporting this issue and going forward to submit a PR. I have add some feedback. Just a few minor comments. I will go on ahead to merge once addressed.

Thank you.

**Comment by kofrasa** [comment]
Changes merged in. Will be available in release 1.2.0
