### ISSUE TITLE
Query for Null or Missing Fields

### ISSUE THREAD

**Issue by ericfong** [kofrasa/mingo#54]
Thanks for your package first. That is really amazing. 

I found that the behavior of `find({ someField: null })` is not same as mongodb

https://docs.mongodb.com/manual/tutorial/query-for-null-fields/

in which null should also match with `undefined` field. 
Shall mingo align that with mongoDb spec? Or that is expected behavior?

BTW. I have done a little benchmark and found that is much faster than `sift` and within same level as `nedb` and `lokijs`. Thanks a lot.

**Comment by kofrasa** [comment]
Hi @ericfong ,

Thanks for reporting this, it is definitely a bug. I am doing some work to move into the new age of es6 ;). I should be able to throw in a fix fairly quickly but a pull request is also welcome.

I appreciate the tiny benchmark done. I am happy to know `Mingo` is not lagging behind in performance given I have mostly prioritized features and MongoDB compatibility. :)

**Comment by ericfong** [comment]
Thanks a lot.
