### ISSUE TITLE
Passing Criteria as a parameter to query.test

### ISSUE THREAD

**Issue by leoncc** [kofrasa/mingo#57]
Hi,

This works (on NodeJS 7.7):
```javascript
  let lowScore = {type: "homework", score: 30};
  let highScore = {type: "homework", score: 80};
  mingo.setup({});
  let query = new mingo.Query({
    type: "homework",
    score: { $gte: 50 }
  });
  let isLowScore = query.test(lowScore);
  console.log("Score Above 50 ", isLowScore);
  let isHighScore = query.test(highScore);
  console.log("Score Above 50 ", isHighScore);
```
and produces:
```
Score Above 50  false
Score Above 50  true
```
The below throws an error *Criteria must be of type Object*. The issue is obviously that *criteria* is initialized as a string and not an object. In my use case I need to read the criteria from a database and from the database it comes back as a string. Is it possible to to this? I know it might be trivial question. 
```javascript
  let lowScore = {type: "homework", score: 30};
  let highScore = {type: "homework", score: 80};
  let criteria = '{type: "homework", score: { $gte: 50 } }';
  mingo.setup({});
  let query = new mingo.Query(criteria);
  let isLowScore = query.test(lowScore);
  console.log("Score Above 50 ", isLowScore);
  let isHighScore = query.test(highScore);
  console.log("Score Above 50 ", isHighScore);
```
Thanks
Leon

**Comment by kofrasa** [comment]
For valid JSON strings you could use `JSON.parse`, otherwise if you trust the source of the data, you can use `eval` (btw, this is NOT recommended)

For example:
```js
// if your string literal is valid JSON (i.e. keys are double-quoted)
let criteria = '{"type": "homework", "score": { "$gte": 50 } }'
let criteriaObj = JSON.parse(criteria)
console.log(typeof criteriaObj) // ==> object
```

using eval
```js
let criteria = '{type: "homework", score: { $gte: 50 } }'
let criteriaObj = eval('(' + criteria + ')')
console.log(typeof criteriaObj) // ==> object
```
See: https://stackoverflow.com/questions/9036429/convert-object-string-to-json

**Comment by leoncc** [comment]
I tried JSON.parse, but experienced issues, for instance with the value part of $regex. eval works fine however - Thank You!!!! I substituted it with the "safe-eval" npm package.
