### ISSUE TITLE
runTest tests are generating false-positives

### ISSUE THREAD

**Issue by saadtazi** [kofrasa/mingo#66]
I found out that [this line](https://github.com/kofrasa/mingo/blob/master/test/support.js#L46) is causing problem: some `runTest` tests that are suppose to fail are not failing because you are comparing `0` with `0` because `isNaN('a string')` or `isNaN([1, 2])` returns true: all the tests that tries to compare strings or arrays are not valid. 

*repro step:*
Try to modify any `runTest` test in `test/string_operators.js` or `test/array_operators.js` to make it fail (hint: it won't!).

I think the proper way to fix it is to do the following: 

```diff
-          if (isNaN(actual) && isNaN(expected)) actual = expected = 0
+          if (actual !== actual && expected !== expected) actual = expected = 0
```
because `NaN === NaN` returns `false`.

There are 3 tests that fails with the suggested changes, 2 related to unicode characters and string operators, that I am not sure how to solve.

**Comment by kofrasa** [comment]
Thanks.

Your fix is correct. I skipped the fact that other types with `isNaN` evaluate to true.

Will look at and address the broken operators
