### ISSUE TITLE
cloneDeep is not cloning all properties when cloning a boolean with false value

### ISSUE THREAD

**Issue by javiercbk** [kofrasa/mingo#72]
From the [$addField](https://docs.mongodb.com/manual/reference/operator/aggregation/addFields/) mongo documentation

> Adds new fields to documents. $addFields outputs documents that contain all existing fields from the input documents and newly added fields.

```js
const { Aggregator } = require('mingo');
const oper = [{
  $addFields:{
    accountInfo:{
      $arrayElemAt:["$accounts", 0]
    }
  }
}];
const col = [{
  _id: "59c52580809dd0032d75238a",
  email: "an@email.com",
  accounts: [{
    createdAt: "2017-09-22T15:00:17.418Z",
    updatedAt: "2017-09-22T15:00:17.418Z",
  }],
}];
const aggregatedCollection = new Aggregator([oper]).run(col);
const expected = [{
  _id: "59c52580809dd0032d75238a",
  email: "an@email.com",
  accountInfo: {
    createdAt: "2017-09-22T15:00:17.418Z",
    updatedAt: "2017-09-22T15:00:17.418Z",
  },
  accounts: [{
    createdAt: "2017-09-22T15:00:17.418Z",
    updatedAt: "2017-09-22T15:00:17.418Z",
  }],
}];

// no accounts array
const got = [{
  _id: "59c52580809dd0032d75238a",
  email: "an@email.com",
  accountInfo: {
    createdAt: "2017-09-22T15:00:17.418Z",
    updatedAt: "2017-09-22T15:00:17.418Z",
  },
}];
```

**Comment by kofrasa** [comment]
Hi @javiercbk 

Thanks for reporting this. 

Please can you confirm if you are using the latest version of `mingo`.

I get the expected output using the latest version `2.0.2`.

```
{
   "_id":"59c52580809dd0032d75238a",
   "email":"an@email.com",
   "accounts":[
      {
         "createdAt":"2017-09-22T15:00:17.418Z",
         "updatedAt":"2017-09-22T15:00:17.418Z"
      }
   ],
   "accountInfo":{
      "createdAt":"2017-09-22T15:00:17.418Z",
      "updatedAt":"2017-09-22T15:00:17.418Z"
   }
}
]
```

**Comment by javiercbk** [comment]
Actually you're right. I'm so sorry for wasting your time, it must be an error on my side.

I'm wrapping your library as a mongo driver and I'm trying to add support to `$lookup` aggregation operation (with the concept of named collection). So I came across with this error yesterday and after a quick debug I thought I pinpointed the error in mingo, but now I can see it is my mistake.

Thanks again

**Comment by javiercbk** [comment]
I've found the issue, the problem is the `cloneDeep` function, it is not cloning the property.

<img width="486" alt="screen shot 2017-09-23 at 6 18 55 pm" src="https://user-images.githubusercontent.com/1448426/30777193-ba84fcc2-a08b-11e7-80ab-5e231ab8f52f.png">

**Comment by javiercbk** [comment]
Pinpointed the issue, when an object has a boolean property with `false` value, cloneDeep will break and stop cloning properties.

```js
it('should cloneDeep object with false property', () => {
    const oper = [{
      $addFields: {
        accountInfo: {
          $arrayElemAt: ['$accounts', 0],
        },
      },
    }];
    const col = [{
      _id: '59c52580809dd0032d75238a',
      email: 'an@email.com',
      deleted: false,
      accounts: [{
        createdAt: '2017-09-22T15:00:17.418Z',
        updatedAt: '2017-09-22T15:00:17.418Z',
      }],
    }];
    const expected = [{
      _id: '59c52580809dd0032d75238a',
      email: 'an@email.com',
      deleted: false,
      accountInfo: {
        createdAt: '2017-09-22T15:00:17.418Z',
        updatedAt: '2017-09-22T15:00:17.418Z',
      },
      accounts: [{
        createdAt: '2017-09-22T15:00:17.418Z',
        updatedAt: '2017-09-22T15:00:17.418Z',
      }],
    }];
    const aggregatedCollection = new Aggregator(oper).run(col);
    expect(expected).to.deep.equal(aggregatedCollection);
  });
```

**Comment by kofrasa** [comment]
I think I have spotted the bug. This is coming from a function depended on by the cloneDeep implementation. Will fix soon
