### ISSUE TITLE
Allow replacing existing operators

### ISSUE THREAD

**Issue by javiercbk** [kofrasa/mingo#74]
Currently the library does not allow to replace existing operations. I believe that replacing an existing operations is a great way to patch something for my use case, why wouldn't allow it?

For example, I reported #73 and I wanted to quickly patch the operation without forking the library but I cannot due this check:

```javascript
assert(!has(operators, op), op + ' already exists for \'' + opClass + '\' operators');
```

**Comment by kofrasa** [comment]
Replacing existing operators is not allowed to avoid unpredictable behaviour. Some operator implementation depend on others internally. If a standard operator is not working as expected, then it should be reported as a bug.

Alternatively you can provide your own [custom operator(https://github.com/kofrasa/mingo/wiki/Custom-Operators) to extend the existing operators for new functionality, or as a stand-in for an existing one until a fix is applied.

**Comment by javiercbk** [comment]
Ok, thanks. I believe this issue will be reopened if more users of this library needs want this beheviour.

As a final statement, I think that if you (developer) are replacing an existing operator, you know that you are introducing a something that might break the library.

Thanks.
