### ISSUE TITLE
Add support for $expr

### ISSUE THREAD

**Issue by felipecarrillo100** [kofrasa/mingo#79]
[mingo.zip](https://github.com/kofrasa/mingo/files/1880004/mingo.zip)

I have modified the mingo.js   from the distribution directory to support the $expr operator.

This operator is introduced in Mongo 3.6 and it allows to use expression (such as arithmetic operations) in a  query.  It also allows comparing 2 fields against eachothr.

Example:
{"$expr":{"$gt":[{"$multiply":["$value1", 2]}, "$value2"]}}

The "$expr" offers advantages over "$where" and it seems easy to implement from the building blocs already available in your implementation. I just had to modify  a few lines  (Do find "$expr").

I'm not sure how to build the project but it would be great if you can add this feature. Use the code in my attachment as reference. 

Thanks in advance

**Comment by kofrasa** [comment]
Thanks for the contribution @felipecarrillo100 I will take a look at this soon.

**Comment by kofrasa** [comment]
Added in commit https://github.com/kofrasa/mingo/commit/4a75f03c20c4e6df7ecde328ceec5a03715efd5e

This will be going in the `2.2.1` release. You can play around with the changes in `branch:development`
