### ISSUE TITLE
Add support for dot notation field names.

### ISSUE THREAD

**Issue by jgornick** [kofrasa/mingo#8]
There doesn't seem to be support for dot notation field names: http://docs.mongodb.org/manual/core/document/#dot-notation

You can currently get around by using the $elemMatch operator.

**Comment by kofrasa** [comment]
Mingo already supports the dot notation. Some test cases do cover them for both object field access and array element access. 
See https://github.com/kofrasa/mingo/blob/master/test/queries.js#L56

I may have forgotten to document the feature and will do so in the next upgrade. If you have any test case that is failing, please let us know.

**Comment by jgornick** [comment]
@kofrasa Meh, I'm sorry, I should of checked tests first. Thanks and great work!

**Comment by kofrasa** [comment]
@jgornick my bad mate. this just reinforces the importance of documentation, so users of the software don't have the need to dive into implementation details to know what is possible or not.
