### ISSUE TITLE
Aggregator $unwind operates on input variable when input variable contains circular links

### ISSUE THREAD

**Issue by felipecarrillo100** [kofrasa/mingo#82]
I'm also having issues with the aggregator when the input array contains circular links. When the input contains circular arrays the $unwind operation seems to modify the input variable instead of making a clone,  

As a consequence some of the fields of the input variable are overwritten, after the $unwind operation.
For instance if you $unwind an array nested in a variable your will have the array replaced by the value of the first element in the array.

data = [{"ob2":{"a":[1,2,34]}},{"ob2":{"a":[4,5,6]}}]

after $unwind the inputs becomes
data = [{"ob2":{"a":1}},  {"ob2":{"a":4]}}]

As a work around I have created a new array without circular links, then everything works fine.

**Comment by kofrasa** [comment]
What version of `mingo` are you running?

**Comment by felipecarrillo100** [comment]
I'm using the very latest version.

This is a hard one to reproduce,  it is happening in the context of my application, so perhaps the error it at my side, the array containing the data has circular links and other stuff.  I will close this issue and let you know later if I find a straight forward way to reproduce.
