### ISSUE TITLE
There is an update mongo style language implementation?

### ISSUE THREAD

**Issue by voxsoftware** [kofrasa/mingo#83]
This is not a bug. Is a question. Like query language, there is an update mongo style language implementation?

**Comment by kofrasa** [comment]
There are no update operators in `mingo`. The scope of the library is only for querying in-memory collections and updates will not be supported in this same package. 

That said, there are dependent libraries that have update support.

https://www.npmjs.com/package/save
https://www.npmjs.com/package/%40creately%2Fmungo
