### ISSUE TITLE
Question: $objectToArray expression must resolve to an object

### ISSUE THREAD

**Issue by graycrow** [kofrasa/mingo#89]
I want to use Aggregation in order to filter an array of objects by the property of a sub object. The problem is that this sub object is not a plain object, but a "class" with a constructor (which boils down to a named function, essentially). Because of this $objectToArray fails with an error `$objectToArray expression must resolve to an object`. It checks if `v.constructor.name` is equal to `object`, but in my case it's a class name. Is there any workaround for this problem except replacing that sub class with an object?

**Comment by kofrasa** [comment]
Perhaps enforcing collection objects to be vanilla JS objects may be too strict, but it might be ok to shift that burden to users. Am happy to accept a PR

**Comment by kofrasa** [comment]
After considering this for a while I think the current behaviour should remain as is. `MongoDB` does not allow storing functions on objects and would translate them to strings. (e.g. `{ "name" : { "code" : "function (n){console.log(n+ \"!\");}" }`) 

If this operator allows custom object types, there is no sensible way to treat function members of the object which might only lead to later failures. I think the right approach is to get an plain Object representation of your custom type to pass to use with `Mingo`.

https://github.com/kofrasa/mingo/blob/master/lib/operators/expression/array.js#L175-L180

I will close this issue. Please reopen if you have some arguments why you think this should be supported.

Thanks.

**Comment by graycrow** [comment]
I understand, no problem.
