### ISSUE TITLE
$slice projection operator throws Type Error for null arrays.

### ISSUE THREAD

**Issue by AntonSotirov** [kofrasa/mingo#9]
If an array field in a document is **null** and we try to project it with a $slice, a type error is thrown.

Expected behaviour is to return null when the array value is null and undefined when the array value is undefined.

**Comment by kofrasa** [comment]
@AntonSotirov could you provide a sample structure to use for a test case

**Comment by kofrasa** [comment]
never mind. pretty simple fix. merging :)

**Comment by kofrasa** [comment]
resolved.
