### ISSUE TITLE
Provide possibility to use only specific operators

### ISSUE THREAD

**Issue by stalniy** [kofrasa/mingo#90]
Hello,

You are working on the awesome project :) And I'd like to use it inside my library. The only issue is bundle size.

So, I want to request possibility to use only specific query operators. For example, I want to use only query operators and simple operators. I don't need projection, agregation, etc.

Do you think you can extract that in some `core` bundle and deliver it separetely (at least its ES6 version)?

**Comment by stalniy** [comment]
Currently minified version of library is `34.3 KB`. I would like core to be around ~ `5-7KB` :)

**Comment by kofrasa** [comment]
Hey @stalniy, I agree with you that this should perhaps be split across different modules.

That has been my plan from the start which gave birth to [mingo-geo](https://github.com/kofrasa/mingo-geo) and [mingo-stream](https://github.com/kofrasa/mingo-stream) packages even though they haven't seem much development since.

I think why I didn't pursue this fully was that the operators weren't that many at the time and the convenience of hosting everything in one package.

I will explore how best to split the functionality into specialised packages and while keeping them amalgamated in this one by taking dependencies.

**Comment by stalniy** [comment]
The easiest way is to use submodules. You can see an example in my repo for `CASL/ability` package (https://github.com/stalniy/casl/tree/master/packages/casl-ability). There is a core + extra package. So, if I want to use only core:

 ```
import ... from '@casl/ability'
```

If I want to use both:

```
import ... from '@casl/ability'
import ... from '@casl/ability/extra'
```

I’d recommend not to split the package into separate npm packages because it will increase infra & support overhead.

**Comment by kofrasa** [comment]
I will look into the module approach. Thanks

**Comment by stalniy** [comment]
What abou implanting something like this:

```js
import { createQuery } from “mingo”
import { lt, gt, eq } from “mingo/operators”

const Query = createQuery({ lt, gt, eq })

const query = new Query({
   userId: 5
})

query.test({ userId: 7 }) // false

const anotherQuery = new Query({
  role: { $in: [...] }
}) // throws exception “unknown $in operator”
```

**Comment by stalniy** [comment]
This should not introduce breaking changes and currently provides version of `Query` can be compiled from all possible operators

**Comment by kofrasa** [comment]
I like the approach even though it is only effective when using `query.test(...)`.

To communicate the limited functionality, the method could be named `createFilterQuery(...)`. The resulting query object could then be of some type, say `FilterQuery` with a limited API interface.

I think it is a good compromise and provides a decent subset for a majority of use cases.

Please feel free to submit a PR.

**Comment by stalniy** [comment]
After reviewing the codebase, I see that it will require a bit more refactoring than I expected.
You have cyclic references (`internal.js` includes all expression operators and some expression operators includes `internal.js`) between files and dynamic operator definitions. So, in order to proceed with the original request, I need to uncycle that files and make static exports.

Instead of 

```js
export const expressionOperators = {
   $abc() {}
}
```

I needs to be 

```js
export function $abs() {}
```

Otherwise tree-shaking (feature of rollup and webpack that removes unused exports) won't work.

The main problem which I currently see is a `computeValue` function

**Comment by kofrasa** [comment]
Yes the operators need to be declared at the top-level and then added to the respective arrays.

You only need to do that for the simple and query operators in https://github.com/kofrasa/mingo/blob/master/lib/operators/query.js for the`FilterQuery` implementation. 

`computeValue` is pervasive and requires knowledge of all available operators to work correctly so doing more than basic filtering will require much deeper changes.

**Comment by kofrasa** [comment]
I have pushed a [dev-filter](https://github.com/kofrasa/mingo/tree/dev-filter) branch in support of my comments above.

This change https://github.com/kofrasa/mingo/commit/5c8e976afc00802a9e1c63d7d402e8a8215214f7 exports the functions for use in the future `createFilterQuery` method. Tree shaking can still work but will be nullified if the user opts to use the `$expr` operator.

We can collaborate on that branch if that is convenient for you.

**Comment by kofrasa** [comment]
The coming `3.0.0` loads only query and projection operators by default. All other operators must be explicitly required and registered. This effectively supports tree shaking to reduce bundle size.

**Comment by kofrasa** [comment]
This is now available on `branch:master`. Specific operators may be imported explicitly and registered using `useOperators`.

Query and Projection operators are imported by default in main modules. This can be side stepped by not importing `mingo` and instead using nested imports such as `mingo/query`, `mingo/core`, etc.

More in readme.

**Comment by kofrasa** [comment]
Release `3.0.0` published
