### ISSUE TITLE
$in operator doesn't properly work for null (similar to $eq issue a few months ago)

### ISSUE THREAD

**Issue by Discordius** [kofrasa/mingo#92]
A few months ago we had the following issue: #54 

The fix seemed to fix it for the $eq query, but turns out there is another way of querying for null fields, which is with the `$in` syntax. We use this all throughout our codebases to check booleans for null values, like this: `field: {$in: [null, false]}`. 

Against Mongo this works fine for undefined fields, but with Mingo this will not properly match on undefined.

**Comment by kofrasa** [comment]
Hi @Discordius, thanks for reporting this bug. 

Can you please provide a full example (data and query) that will work and the expected result?

**Comment by kofrasa** [comment]
Closing this issue. Reopen with a example and the version of `mingo` if it is still broken
