### ISSUE TITLE
How to use Mingo with arrays of custom objects

### ISSUE THREAD

**Issue by fabiosussetto** [kofrasa/mingo#94]
Hi, thanks for this amazing library.
I'm playing around with Mingo and I've got an array of Mobx objects (basically observables). I can turn them into plain objects easily, but I'd like to get back from Mingo queries the same objects. Maybe this is not supported at all cause of Mongodb projections support (e.g. what should I get back if I use $addFields on one of my objects?) - how would you approach this anyway?

Thanks!

**Comment by kofrasa** [comment]
Hi @fabiosussetto

I am glad you find this library useful. Unfortunately custom objects aren't supported.

The challenge is that there is no consistent way to clone them. It also messes with the implementation of the aggregation pipeline operators like `$project`, `$unwind`, `addFields` etc.
As a result custom objects are treated as plain JS objects where possible with strict validation when not allowed. For now, running the result through your own transform function is the way to go.

Thanks
