### ISSUE TITLE
$dateFromParts not supported?

### ISSUE THREAD

**Issue by fabiosussetto** [kofrasa/mingo#97]
Hi, first of all thanks for your amazing work on this project.
I wonder if currently the $dateFromParts operator is missing/not supported. I checked the source code and couldn't find any reference to it. Is there a particular reason why it's not been implemented?

Thanks.

**Comment by kofrasa** [comment]
Hi @fabiosussetto thanks for finding the library useful.

I don't think `$dateFromParts ` is supported yet. I am happy to accept a PR.

**Comment by kofrasa** [comment]
Coming in `3.0.0`. Currently available on `branch:master`
